// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_transition_event_document_embedding.sql

package queries

import (
	"context"
)

const createTransitionEventDocumentEmbedding = `-- name: CreateTransitionEventDocumentEmbedding :exec
INSERT INTO transition_event_document_float32_embeddings (transition_event_document_id, embedding)
VALUES (?, ?)
`

type CreateTransitionEventDocumentEmbeddingParams struct {
	TransitionEventDocumentID int64
	Embedding                 string
}

func (q *Queries) CreateTransitionEventDocumentEmbedding(ctx context.Context, arg CreateTransitionEventDocumentEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, createTransitionEventDocumentEmbedding, arg.TransitionEventDocumentID, arg.Embedding)
	return err
}
