// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_transition_event_document.sql

package queries

import (
	"context"
	"database/sql"
)

const createTransitionEventDocument = `-- name: CreateTransitionEventDocument :one
INSERT INTO transition_event_documents (transition_event_id, content, embedding_model, embedding_dimension, embedded_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateTransitionEventDocumentParams struct {
	TransitionEventID  int64
	Content            string
	EmbeddingModel     string
	EmbeddingDimension int64
	EmbeddedAt         sql.NullTime
}

func (q *Queries) CreateTransitionEventDocument(ctx context.Context, arg CreateTransitionEventDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTransitionEventDocument,
		arg.TransitionEventID,
		arg.Content,
		arg.EmbeddingModel,
		arg.EmbeddingDimension,
		arg.EmbeddedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
