// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_semantic_document_embedding.sql

package queries

import (
	"context"
)

const createSemanticDocumentEmbedding = `-- name: CreateSemanticDocumentEmbedding :exec
INSERT INTO semantic_document_float32_embeddings (semantic_document_id, embedding)
VALUES (?, ?)
`

type CreateSemanticDocumentEmbeddingParams struct {
	SemanticDocumentID int64
	Embedding          string
}

func (q *Queries) CreateSemanticDocumentEmbedding(ctx context.Context, arg CreateSemanticDocumentEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, createSemanticDocumentEmbedding, arg.SemanticDocumentID, arg.Embedding)
	return err
}
