// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_transition_event.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createTransitionEvent = `-- name: CreateTransitionEvent :one
INSERT INTO transition_events (application_id, started_at, ended_at)
VALUES (?, ?, ?)
RETURNING id
`

type CreateTransitionEventParams struct {
	ApplicationID sql.NullInt64
	StartedAt     time.Time
	EndedAt       time.Time
}

func (q *Queries) CreateTransitionEvent(ctx context.Context, arg CreateTransitionEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTransitionEvent, arg.ApplicationID, arg.StartedAt, arg.EndedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}
