// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_transition_event_metadata.sql

package queries

import (
	"context"
	"database/sql"
)

const createTransitionEventMetadata = `-- name: CreateTransitionEventMetadata :exec
INSERT INTO transition_event_metadata (transition_event_id, browser, tab, idle, cdp_url, pid)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTransitionEventMetadataParams struct {
	TransitionEventID int64
	Browser           bool
	Tab               *string
	Idle              bool
	CdpUrl            *string
	Pid               sql.NullInt64
}

func (q *Queries) CreateTransitionEventMetadata(ctx context.Context, arg CreateTransitionEventMetadataParams) error {
	_, err := q.db.ExecContext(ctx, createTransitionEventMetadata,
		arg.TransitionEventID,
		arg.Browser,
		arg.Tab,
		arg.Idle,
		arg.CdpUrl,
		arg.Pid,
	)
	return err
}
