// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_semantic_document_embedding.sql

package queries

import (
	"context"
)

const deleteSemanticDocumentEmbedding = `-- name: DeleteSemanticDocumentEmbedding :exec
DELETE FROM semantic_document_float32_embeddings
WHERE semantic_document_id = ?
`

func (q *Queries) DeleteSemanticDocumentEmbedding(ctx context.Context, semanticDocumentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSemanticDocumentEmbedding, semanticDocumentID)
	return err
}
