// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_transition_event_document_embedding.sql

package queries

import (
	"context"
)

const deleteTransitionEventDocumentEmbedding = `-- name: DeleteTransitionEventDocumentEmbedding :exec
DELETE FROM transition_event_document_float32_embeddings
WHERE transition_event_document_id = ?
`

func (q *Queries) DeleteTransitionEventDocumentEmbedding(ctx context.Context, transitionEventDocumentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransitionEventDocumentEmbedding, transitionEventDocumentID)
	return err
}
