// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_semantic_index_counts.sql

package queries

import (
	"context"
)

const getSemanticIndexCounts = `-- name: GetSemanticIndexCounts :one
SELECT
  (SELECT COUNT(*) FROM transition_events) AS completed_event_count,
  (
    SELECT COUNT(*)
    FROM semantic_documents
    WHERE document_type = 'event'
  ) AS indexed_event_count,
  (
    SELECT COUNT(*)
    FROM semantic_documents
    JOIN semantic_document_embeddings
      ON semantic_document_embeddings.semantic_document_id = semantic_documents.id
    WHERE semantic_documents.document_type = 'event'
      AND semantic_document_embeddings.embedding_model = ?
  ) AS embedded_event_count
`

type GetSemanticIndexCountsRow struct {
	CompletedEventCount int64
	IndexedEventCount   int64
	EmbeddedEventCount  int64
}

func (q *Queries) GetSemanticIndexCounts(ctx context.Context, embeddingModel string) (GetSemanticIndexCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getSemanticIndexCounts, embeddingModel)
	var i GetSemanticIndexCountsRow
	err := row.Scan(&i.CompletedEventCount, &i.IndexedEventCount, &i.EmbeddedEventCount)
	return i, err
}
