// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_transition_events.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const getTransitionEvents = `-- name: GetTransitionEvents :many
SELECT
  transition_events.id AS transition_event_id,
  applications.name AS application_name,
  applications.platform_identifier AS application_platform_identifier,
  applications.path AS application_path,
  transition_event_reasons.reason AS reason,
  transition_events.started_at,
  transition_events.ended_at,
  transition_event_metadata.browser,
  transition_event_metadata.tab,
  transition_event_metadata.idle,
  transition_event_metadata.cdp_url,
  transition_event_metadata.pid
FROM transition_events
JOIN transition_event_reasons ON transition_event_reasons.id = transition_events.transition_reason_id
LEFT JOIN applications ON applications.id = transition_events.application_id
LEFT JOIN transition_event_metadata ON transition_event_metadata.transition_event_id = transition_events.id
WHERE (?1 IS NULL OR transition_events.started_at >= ?1)
  AND (?2 IS NULL OR transition_events.ended_at <= ?2)
ORDER BY transition_events.started_at ASC, transition_events.id ASC
`

type GetTransitionEventsParams struct {
	StartedAt interface{}
	EndedAt   interface{}
}

type GetTransitionEventsRow struct {
	TransitionEventID             int64
	ApplicationName               sql.NullString
	ApplicationPlatformIdentifier sql.NullString
	ApplicationPath               sql.NullString
	Reason                        string
	StartedAt                     time.Time
	EndedAt                       time.Time
	Browser                       sql.NullBool
	Tab                           *string
	Idle                          sql.NullBool
	CdpUrl                        *string
	Pid                           sql.NullInt64
}

func (q *Queries) GetTransitionEvents(ctx context.Context, arg GetTransitionEventsParams) ([]GetTransitionEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransitionEvents, arg.StartedAt, arg.EndedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransitionEventsRow
	for rows.Next() {
		var i GetTransitionEventsRow
		if err := rows.Scan(
			&i.TransitionEventID,
			&i.ApplicationName,
			&i.ApplicationPlatformIdentifier,
			&i.ApplicationPath,
			&i.Reason,
			&i.StartedAt,
			&i.EndedAt,
			&i.Browser,
			&i.Tab,
			&i.Idle,
			&i.CdpUrl,
			&i.Pid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
