// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_transition_event_document_sources_for_window.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const listTransitionEventDocumentSourcesForWindow = `-- name: ListTransitionEventDocumentSourcesForWindow :many
SELECT
  transition_events.id AS transition_event_id,
  applications.name AS application_name,
  transition_event_reasons.reason AS reason,
  transition_events.started_at,
  transition_events.ended_at,
  transition_event_metadata.browser,
  transition_event_metadata.tab,
  transition_event_metadata.idle,
  transition_event_metadata.cdp_url
FROM transition_events
JOIN transition_event_reasons ON transition_event_reasons.id = transition_events.transition_reason_id
LEFT JOIN applications ON applications.id = transition_events.application_id
LEFT JOIN transition_event_metadata ON transition_event_metadata.transition_event_id = transition_events.id
WHERE transition_events.started_at < ?1
  AND transition_events.ended_at > ?2
ORDER BY transition_events.started_at ASC, transition_events.id ASC
`

type ListTransitionEventDocumentSourcesForWindowParams struct {
	WindowEndedAt   time.Time
	WindowStartedAt time.Time
}

type ListTransitionEventDocumentSourcesForWindowRow struct {
	TransitionEventID int64
	ApplicationName   sql.NullString
	Reason            string
	StartedAt         time.Time
	EndedAt           time.Time
	Browser           sql.NullBool
	Tab               *string
	Idle              sql.NullBool
	CdpUrl            *string
}

func (q *Queries) ListTransitionEventDocumentSourcesForWindow(ctx context.Context, arg ListTransitionEventDocumentSourcesForWindowParams) ([]ListTransitionEventDocumentSourcesForWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransitionEventDocumentSourcesForWindow, arg.WindowEndedAt, arg.WindowStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransitionEventDocumentSourcesForWindowRow
	for rows.Next() {
		var i ListTransitionEventDocumentSourcesForWindowRow
		if err := rows.Scan(
			&i.TransitionEventID,
			&i.ApplicationName,
			&i.Reason,
			&i.StartedAt,
			&i.EndedAt,
			&i.Browser,
			&i.Tab,
			&i.Idle,
			&i.CdpUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
