// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_missing_semantic_event_document_ids.sql

package queries

import (
	"context"
)

const listMissingSemanticEventDocumentIDs = `-- name: ListMissingSemanticEventDocumentIDs :many
SELECT transition_events.id
FROM transition_events
LEFT JOIN semantic_documents
  ON semantic_documents.transition_event_id = transition_events.id
  AND semantic_documents.document_type = 'event'
LEFT JOIN semantic_document_float32_embeddings
  ON semantic_document_float32_embeddings.semantic_document_id = semantic_documents.id
WHERE semantic_documents.id IS NULL
   OR semantic_document_float32_embeddings.id IS NULL
ORDER BY transition_events.started_at DESC, transition_events.id DESC
LIMIT ?
`

func (q *Queries) ListMissingSemanticEventDocumentIDs(ctx context.Context, limit int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listMissingSemanticEventDocumentIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
