// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package queries

import (
	"context"
)

const deleteMetadata = `-- name: DeleteMetadata :exec
DELETE FROM app_metadata
WHERE key = ?
`

func (q *Queries) DeleteMetadata(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteMetadata, key)
	return err
}

const getMetadata = `-- name: GetMetadata :one
SELECT key, value
FROM app_metadata
WHERE key = ?
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (AppMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var i AppMetadatum
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const listMetadata = `-- name: ListMetadata :many
SELECT key, value
FROM app_metadata
ORDER BY key
`

func (q *Queries) ListMetadata(ctx context.Context) ([]AppMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMetadatum
	for rows.Next() {
		var i AppMetadatum
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMetadata = `-- name: SetMetadata :exec
INSERT INTO app_metadata (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetMetadataParams struct {
	Key   string
	Value string
}

func (q *Queries) SetMetadata(ctx context.Context, arg SetMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setMetadata, arg.Key, arg.Value)
	return err
}
