// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type Application struct {
	ID                 int64
	Name               string
	PlatformIdentifier sql.NullString
	Path               sql.NullString
}

type SemanticDocument struct {
	ID                 int64
	DocumentKey        string
	DocumentType       string
	TransitionEventID  sql.NullInt64
	StartedAt          sql.NullTime
	EndedAt            sql.NullTime
	Content            string
	EmbeddingModel     string
	EmbeddingDimension int64
	EmbeddedAt         sql.NullTime
}

type SemanticDocumentFloat32Embedding struct {
	ID                 int64
	SemanticDocumentID int64
	Embedding          string
	K                  sql.NullInt64
	Distance           sql.NullFloat64
}

type TransitionEvent struct {
	ID                 int64
	ApplicationID      sql.NullInt64
	TransitionReasonID int64
	StartedAt          time.Time
	EndedAt            time.Time
}

type TransitionEventMetadatum struct {
	ID                int64
	TransitionEventID int64
	Browser           bool
	Tab               *string
	Idle              bool
	CdpUrl            *string
}

type TransitionEventReason struct {
	ID     int64
	Reason string
}
