// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type Application struct {
	ID   int64
	Name string
}

type TransitionEvent struct {
	ID                 int64
	ApplicationID      sql.NullInt64
	TransitionReasonID int64
	StartedAt          time.Time
	EndedAt            time.Time
}

type TransitionEventMetadatum struct {
	ID                int64
	TransitionEventID int64
	Browser           bool
	Tab               *string
	Idle              bool
	CdpUrl            *string
}

type TransitionEventReason struct {
	ID     int64
	Reason string
}
