// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package queries

import (
	"context"
	"time"
)

const countProjectsByID = `-- name: CountProjectsByID :one
SELECT COUNT(*) FROM projects WHERE id = ?
`

func (q *Queries) CountProjectsByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsByName = `-- name: CountProjectsByName :one
SELECT COUNT(*) FROM projects WHERE name = ? COLLATE NOCASE
`

func (q *Queries) CountProjectsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  id,
  name,
  color_argb,
  client,
  hourly_rate_cents,
  created_at,
  updated_at
)
VALUES (?, ?, ?, '', 0, ?, ?)
RETURNING
  id,
  name,
  color_argb,
  client,
  hourly_rate_cents,
  created_at,
  updated_at
`

type CreateProjectParams struct {
	ID        string
	Name      string
	ColorArgb int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.ColorArgb,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorArgb,
		&i.Client,
		&i.HourlyRateCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT
  id,
  name,
  color_argb,
  client,
  hourly_rate_cents,
  created_at,
  updated_at
FROM projects
ORDER BY created_at, name COLLATE NOCASE, id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorArgb,
			&i.Client,
			&i.HourlyRateCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
