// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	DeleteMetadata(ctx context.Context, key string) error
	GetMetadata(ctx context.Context, key string) (AppMetadatum, error)
	ListMetadata(ctx context.Context) ([]AppMetadatum, error)
	SetMetadata(ctx context.Context, arg SetMetadataParams) error
}

var _ Querier = (*Queries)(nil)
