// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
)

type Querier interface {
	CreateSemanticDocumentEmbedding(ctx context.Context, arg CreateSemanticDocumentEmbeddingParams) error
	CreateTransitionEvent(ctx context.Context, arg CreateTransitionEventParams) (int64, error)
	CreateTransitionEventMetadata(ctx context.Context, arg CreateTransitionEventMetadataParams) error
	DeleteSemanticDocumentEmbedding(ctx context.Context, semanticDocumentID int64) error
	GetSemanticEventDocumentSource(ctx context.Context, id int64) (GetSemanticEventDocumentSourceRow, error)
	GetSemanticIndexCounts(ctx context.Context) (GetSemanticIndexCountsRow, error)
	GetTransitionEvent(ctx context.Context, id int64) (GetTransitionEventRow, error)
	GetTransitionEvents(ctx context.Context, arg GetTransitionEventsParams) ([]GetTransitionEventsRow, error)
	ListMissingSemanticEventDocumentIDs(ctx context.Context, limit int64) ([]int64, error)
	ListTransitionEventDocumentSourcesForWindow(ctx context.Context, arg ListTransitionEventDocumentSourcesForWindowParams) ([]ListTransitionEventDocumentSourcesForWindowRow, error)
	SearchSemanticDocuments(ctx context.Context, arg SearchSemanticDocumentsParams) ([]SearchSemanticDocumentsRow, error)
	UpsertApplication(ctx context.Context, arg UpsertApplicationParams) (int64, error)
	UpsertSemanticDocument(ctx context.Context, arg UpsertSemanticDocumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
