// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_semantic_documents.sql

package queries

import (
	"context"
	"database/sql"
)

const searchSemanticDocuments = `-- name: SearchSemanticDocuments :many
WITH matches AS (
  SELECT semantic_document_id, distance
  FROM semantic_document_float32_embeddings
  WHERE embedding MATCH ?
    AND k = ?
)
SELECT
  semantic_documents.id,
  semantic_documents.document_key,
  semantic_documents.document_type,
  semantic_documents.transition_event_id,
  semantic_documents.started_at,
  semantic_documents.ended_at,
  semantic_documents.content,
  matches.distance
FROM matches
JOIN semantic_documents ON semantic_documents.id = matches.semantic_document_id
ORDER BY matches.distance
`

type SearchSemanticDocumentsParams struct {
	Embedding string
	K         sql.NullInt64
}

type SearchSemanticDocumentsRow struct {
	ID                int64
	DocumentKey       string
	DocumentType      string
	TransitionEventID sql.NullInt64
	StartedAt         sql.NullTime
	EndedAt           sql.NullTime
	Content           string
	Distance          sql.NullFloat64
}

func (q *Queries) SearchSemanticDocuments(ctx context.Context, arg SearchSemanticDocumentsParams) ([]SearchSemanticDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSemanticDocuments, arg.Embedding, arg.K)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSemanticDocumentsRow
	for rows.Next() {
		var i SearchSemanticDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentKey,
			&i.DocumentType,
			&i.TransitionEventID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Content,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
