// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_transition_event_documents.sql

package queries

import (
	"context"
	"database/sql"
)

const searchTransitionEventDocuments = `-- name: SearchTransitionEventDocuments :many
WITH matches AS (
  SELECT transition_event_document_id, distance
  FROM transition_event_document_float32_embeddings
  WHERE embedding MATCH ?
    AND k = ?
)
SELECT
  transition_event_documents.transition_event_id,
  transition_event_documents.content,
  matches.distance
FROM matches
JOIN transition_event_documents ON transition_event_documents.id = matches.transition_event_document_id
ORDER BY matches.distance
`

type SearchTransitionEventDocumentsParams struct {
	Embedding string
	K         sql.NullInt64
}

type SearchTransitionEventDocumentsRow struct {
	TransitionEventID int64
	Content           string
	Distance          sql.NullFloat64
}

func (q *Queries) SearchTransitionEventDocuments(ctx context.Context, arg SearchTransitionEventDocumentsParams) ([]SearchTransitionEventDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTransitionEventDocuments, arg.Embedding, arg.K)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTransitionEventDocumentsRow
	for rows.Next() {
		var i SearchTransitionEventDocumentsRow
		if err := rows.Scan(&i.TransitionEventID, &i.Content, &i.Distance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
