// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timesheets.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createTimesheet = `-- name: CreateTimesheet :one
INSERT INTO timesheets (
  id,
  started_at,
  ended_at,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING
  id,
  started_at,
  ended_at,
  created_at,
  updated_at
`

type CreateTimesheetParams struct {
	ID        string
	StartedAt time.Time
	EndedAt   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTimesheet(ctx context.Context, arg CreateTimesheetParams) (Timesheet, error) {
	row := q.db.QueryRowContext(ctx, createTimesheet,
		arg.ID,
		arg.StartedAt,
		arg.EndedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Timesheet
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimesheetEntry = `-- name: CreateTimesheetEntry :one
INSERT INTO timesheet_entries (
  id,
  timesheet_id,
  project_id,
  title,
  notes,
  start_minute,
  duration_minutes,
  billable,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
  id,
  timesheet_id,
  project_id,
  title,
  notes,
  start_minute,
  duration_minutes,
  billable,
  created_at,
  updated_at
`

type CreateTimesheetEntryParams struct {
	ID              string
	TimesheetID     string
	ProjectID       sql.NullString
	Title           string
	Notes           string
	StartMinute     int64
	DurationMinutes int64
	Billable        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateTimesheetEntry(ctx context.Context, arg CreateTimesheetEntryParams) (TimesheetEntry, error) {
	row := q.db.QueryRowContext(ctx, createTimesheetEntry,
		arg.ID,
		arg.TimesheetID,
		arg.ProjectID,
		arg.Title,
		arg.Notes,
		arg.StartMinute,
		arg.DurationMinutes,
		arg.Billable,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TimesheetEntry
	err := row.Scan(
		&i.ID,
		&i.TimesheetID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.StartMinute,
		&i.DurationMinutes,
		&i.Billable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimesheetEntryUsageBlock = `-- name: CreateTimesheetEntryUsageBlock :exec
INSERT INTO timesheet_entry_usage_blocks (
  timesheet_entry_id,
  usage_id,
  sort_order
)
VALUES (?, ?, ?)
`

type CreateTimesheetEntryUsageBlockParams struct {
	TimesheetEntryID string
	UsageID          string
	SortOrder        int64
}

func (q *Queries) CreateTimesheetEntryUsageBlock(ctx context.Context, arg CreateTimesheetEntryUsageBlockParams) error {
	_, err := q.db.ExecContext(ctx, createTimesheetEntryUsageBlock, arg.TimesheetEntryID, arg.UsageID, arg.SortOrder)
	return err
}

const deleteTimesheetEntry = `-- name: DeleteTimesheetEntry :exec
DELETE FROM timesheet_entries
WHERE id = ?
`

func (q *Queries) DeleteTimesheetEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTimesheetEntry, id)
	return err
}

const getTimesheetByWindow = `-- name: GetTimesheetByWindow :one
SELECT
  id,
  started_at,
  ended_at,
  created_at,
  updated_at
FROM timesheets
WHERE started_at = ? AND ended_at = ?
LIMIT 1
`

type GetTimesheetByWindowParams struct {
	StartedAt time.Time
	EndedAt   time.Time
}

func (q *Queries) GetTimesheetByWindow(ctx context.Context, arg GetTimesheetByWindowParams) (Timesheet, error) {
	row := q.db.QueryRowContext(ctx, getTimesheetByWindow, arg.StartedAt, arg.EndedAt)
	var i Timesheet
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimesheetEntries = `-- name: ListTimesheetEntries :many
SELECT
  timesheet_entries.id,
  timesheet_entries.timesheet_id,
  timesheet_entries.project_id,
  timesheet_entries.title,
  timesheet_entries.notes,
  timesheet_entries.start_minute,
  timesheet_entries.duration_minutes,
  timesheet_entries.billable,
  timesheet_entries.created_at,
  timesheet_entries.updated_at
FROM timesheet_entries
JOIN timesheets ON timesheets.id = timesheet_entries.timesheet_id
WHERE timesheets.started_at = ? AND timesheets.ended_at = ?
ORDER BY timesheet_entries.start_minute, timesheet_entries.created_at, timesheet_entries.id
`

type ListTimesheetEntriesParams struct {
	StartedAt time.Time
	EndedAt   time.Time
}

func (q *Queries) ListTimesheetEntries(ctx context.Context, arg ListTimesheetEntriesParams) ([]TimesheetEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntries, arg.StartedAt, arg.EndedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimesheetEntry
	for rows.Next() {
		var i TimesheetEntry
		if err := rows.Scan(
			&i.ID,
			&i.TimesheetID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.StartMinute,
			&i.DurationMinutes,
			&i.Billable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimesheetEntriesInRange = `-- name: ListTimesheetEntriesInRange :many
SELECT
  timesheets.started_at,
  timesheets.ended_at,
  timesheet_entries.id,
  timesheet_entries.timesheet_id,
  timesheet_entries.project_id,
  timesheet_entries.title,
  timesheet_entries.notes,
  timesheet_entries.start_minute,
  timesheet_entries.duration_minutes,
  timesheet_entries.billable,
  timesheet_entries.created_at,
  timesheet_entries.updated_at
FROM timesheet_entries
JOIN timesheets ON timesheets.id = timesheet_entries.timesheet_id
WHERE timesheets.started_at >= ? AND timesheets.started_at < ?
ORDER BY timesheets.started_at, timesheet_entries.start_minute, timesheet_entries.created_at, timesheet_entries.id
`

type ListTimesheetEntriesInRangeParams struct {
	StartedAt   time.Time
	StartedAt_2 time.Time
}

type ListTimesheetEntriesInRangeRow struct {
	StartedAt       time.Time
	EndedAt         time.Time
	ID              string
	TimesheetID     string
	ProjectID       sql.NullString
	Title           string
	Notes           string
	StartMinute     int64
	DurationMinutes int64
	Billable        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListTimesheetEntriesInRange(ctx context.Context, arg ListTimesheetEntriesInRangeParams) ([]ListTimesheetEntriesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntriesInRange, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimesheetEntriesInRangeRow
	for rows.Next() {
		var i ListTimesheetEntriesInRangeRow
		if err := rows.Scan(
			&i.StartedAt,
			&i.EndedAt,
			&i.ID,
			&i.TimesheetID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.StartMinute,
			&i.DurationMinutes,
			&i.Billable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimesheetEntryUsageBlocks = `-- name: ListTimesheetEntryUsageBlocks :many
SELECT usage_id
FROM timesheet_entry_usage_blocks
WHERE timesheet_entry_id = ?
ORDER BY sort_order, usage_id
`

func (q *Queries) ListTimesheetEntryUsageBlocks(ctx context.Context, timesheetEntryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntryUsageBlocks, timesheetEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var usage_id string
		if err := rows.Scan(&usage_id); err != nil {
			return nil, err
		}
		items = append(items, usage_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
