// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_application.sql

package queries

import (
	"context"
)

const upsertApplication = `-- name: UpsertApplication :one
INSERT INTO applications (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id
`

func (q *Queries) UpsertApplication(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertApplication, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
