// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_transition_event_document.sql

package queries

import (
	"context"
	"database/sql"
)

const upsertTransitionEventDocument = `-- name: UpsertTransitionEventDocument :one
INSERT INTO transition_event_documents (transition_event_id, content, embedding_model, embedding_dimension, embedded_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(transition_event_id) DO UPDATE SET
  content = excluded.content,
  embedding_model = excluded.embedding_model,
  embedding_dimension = excluded.embedding_dimension,
  embedded_at = excluded.embedded_at
RETURNING id
`

type UpsertTransitionEventDocumentParams struct {
	TransitionEventID  int64
	Content            string
	EmbeddingModel     string
	EmbeddingDimension int64
	EmbeddedAt         sql.NullTime
}

func (q *Queries) UpsertTransitionEventDocument(ctx context.Context, arg UpsertTransitionEventDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTransitionEventDocument,
		arg.TransitionEventID,
		arg.Content,
		arg.EmbeddingModel,
		arg.EmbeddingDimension,
		arg.EmbeddedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
