// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_ai_settings.sql

package queries

import (
	"context"
	"time"
)

const upsertAISettings = `-- name: UpsertAISettings :exec
INSERT INTO ai_settings (
  id,
  provider,
  openrouter_base_url,
  ollama_base_url,
  embedding_model_id,
  semantic_model_id,
  updated_at
)
VALUES (1, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  provider = excluded.provider,
  openrouter_base_url = excluded.openrouter_base_url,
  ollama_base_url = excluded.ollama_base_url,
  embedding_model_id = excluded.embedding_model_id,
  semantic_model_id = excluded.semantic_model_id,
  updated_at = excluded.updated_at
`

type UpsertAISettingsParams struct {
	Provider          string
	OpenrouterBaseUrl string
	OllamaBaseUrl     string
	EmbeddingModelID  int64
	SemanticModelID   int64
	UpdatedAt         time.Time
}

func (q *Queries) UpsertAISettings(ctx context.Context, arg UpsertAISettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAISettings,
		arg.Provider,
		arg.OpenrouterBaseUrl,
		arg.OllamaBaseUrl,
		arg.EmbeddingModelID,
		arg.SemanticModelID,
		arg.UpdatedAt,
	)
	return err
}
