// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_transition_event_now.sql

package writequeries

import (
	"context"
	"database/sql"
)

const createTransitionEventNow = `-- name: CreateTransitionEventNow :one
INSERT INTO transition_events (application_id, transition_reason_id)
VALUES (?, (SELECT id FROM transition_event_reasons WHERE reason = ?))
RETURNING id
`

type CreateTransitionEventNowParams struct {
	ApplicationID sql.NullInt64
	Reason        string
}

func (q *Queries) CreateTransitionEventNow(ctx context.Context, arg CreateTransitionEventNowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTransitionEventNow, arg.ApplicationID, arg.Reason)
	var id int64
	err := row.Scan(&id)
	return id, err
}
