// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_foreground_process_metadata.sql

package writequeries

import (
	"context"
)

const createForegroundProcessMetadata = `-- name: CreateForegroundProcessMetadata :exec
INSERT INTO foreground_process_metadata (foreground_process_id, browser, idle, tab, cdp_url, latitude, longitude, public_ip)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(foreground_process_id) DO NOTHING
`

type CreateForegroundProcessMetadataParams struct {
	ForegroundProcessID int64
	Browser             bool
	Idle                bool
	Tab                 *string
	CdpUrl              *string
	Latitude            *float64
	Longitude           *float64
	PublicIp            *string
}

func (q *Queries) CreateForegroundProcessMetadata(ctx context.Context, arg CreateForegroundProcessMetadataParams) error {
	_, err := q.db.ExecContext(ctx, createForegroundProcessMetadata,
		arg.ForegroundProcessID,
		arg.Browser,
		arg.Idle,
		arg.Tab,
		arg.CdpUrl,
		arg.Latitude,
		arg.Longitude,
		arg.PublicIp,
	)
	return err
}
