// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_timeline.sql

package writequeries

import (
	"context"
	"database/sql"
)

const createTimeline = `-- name: CreateTimeline :one
INSERT INTO timeline (initial_foreground_process_id, end_foreground_process_id)
VALUES (?, ?)
RETURNING id
`

type CreateTimelineParams struct {
	InitialForegroundProcessID sql.NullInt64
	EndForegroundProcessID     sql.NullInt64
}

func (q *Queries) CreateTimeline(ctx context.Context, arg CreateTimelineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTimeline, arg.InitialForegroundProcessID, arg.EndForegroundProcessID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
