// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_timeline_embedding.sql

package writequeries

import (
	"context"
	"database/sql"
)

const createTimelineEmbedding = `-- name: CreateTimelineEmbedding :exec
INSERT INTO timeline_embeddings (
  timeline_id,
  timeline_semantic_documents_id,
  embedding_model_id,
  dimension,
  embedding
)
VALUES (?, ?, ?, ?, ?)
`

type CreateTimelineEmbeddingParams struct {
	TimelineID                  sql.NullInt64
	TimelineSemanticDocumentsID sql.NullInt64
	EmbeddingModelID            sql.NullInt64
	Dimension                   int64
	Embedding                   []byte
}

func (q *Queries) CreateTimelineEmbedding(ctx context.Context, arg CreateTimelineEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, createTimelineEmbedding,
		arg.TimelineID,
		arg.TimelineSemanticDocumentsID,
		arg.EmbeddingModelID,
		arg.Dimension,
		arg.Embedding,
	)
	return err
}
