// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_timeline_embedding.sql

package writequeries

import (
	"context"
	"database/sql"
)

const deleteTimelineEmbedding = `-- name: DeleteTimelineEmbedding :exec
DELETE FROM timeline_embeddings
WHERE timeline_semantic_documents_id = ?
`

func (q *Queries) DeleteTimelineEmbedding(ctx context.Context, timelineSemanticDocumentsID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTimelineEmbedding, timelineSemanticDocumentsID)
	return err
}
