// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_timeline.sql

package writequeries

import (
	"context"
)

const deleteTimeline = `-- name: DeleteTimeline :exec
DELETE FROM timeline WHERE id = ?
`

func (q *Queries) DeleteTimeline(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTimeline, id)
	return err
}
