// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_masked_category.sql

package writequeries

import (
	"context"
)

const insertMaskedCategory = `-- name: InsertMaskedCategory :exec
INSERT INTO masked_categories (application_categories_id, masked_application_categories_id)
VALUES (
    (SELECT application_categories.id FROM application_categories WHERE application_categories.category_id = ?1),
    (SELECT application_categories.id FROM application_categories WHERE application_categories.category_id = ?2)
)
ON CONFLICT DO NOTHING
`

type InsertMaskedCategoryParams struct {
	CategoryID       int64
	MaskedCategoryID int64
}

func (q *Queries) InsertMaskedCategory(ctx context.Context, arg InsertMaskedCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMaskedCategory, arg.CategoryID, arg.MaskedCategoryID)
	return err
}
