// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package writequeries

import (
	"database/sql"
)

type LedgerItem struct {
	ID           int64
	LedgerID     sql.NullInt64
	Billable     bool
	Title        string
	Notes        sql.NullString
	StartedAtUtc sql.NullTime
	EndedAtUtc   sql.NullTime
}
