// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package writequeries

import (
	"time"
)

type LedgerItem struct {
	ID           int64
	LedgerID     *int64
	Billable     bool
	Title        string
	Notes        *string
	StartedAtUtc *time.Time
	EndedAtUtc   *time.Time
}
