// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package writequeries

import (
	"context"
	"time"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  id,
  name,
  color_argb,
  client,
  hourly_rate_cents,
  created_at,
  updated_at
)
VALUES (?, ?, ?, '', 0, ?, ?)
ON CONFLICT (id) DO NOTHING
RETURNING
  id,
  name,
  color_argb,
  client,
  hourly_rate_cents,
  created_at,
  updated_at
`

type CreateProjectParams struct {
	ID        string
	Name      string
	ColorArgb int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.ColorArgb,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ColorArgb,
		&i.Client,
		&i.HourlyRateCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}
