// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package writequeries

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name)
VALUES (?)
RETURNING id
`

func (q *Queries) CreateProject(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createProject, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProjectDetails = `-- name: CreateProjectDetails :exec
INSERT INTO project_details (projects_id, project_colors_id, costing_type_id, rate)
VALUES (?, ?, ?, ?)
`

type CreateProjectDetailsParams struct {
	ProjectsID      *int64
	ProjectColorsID *int64
	CostingTypeID   *int64
	Rate            *int64
}

func (q *Queries) CreateProjectDetails(ctx context.Context, arg CreateProjectDetailsParams) error {
	_, err := q.db.ExecContext(ctx, createProjectDetails,
		arg.ProjectsID,
		arg.ProjectColorsID,
		arg.CostingTypeID,
		arg.Rate,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}
