// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package writequeries

import (
	"context"
)

type Querier interface {
	CreateLedgerItem(ctx context.Context, arg CreateLedgerItemParams) (LedgerItem, error)
	CreateLedgerItemTimelineEntry(ctx context.Context, arg CreateLedgerItemTimelineEntryParams) error
	CreateProject(ctx context.Context, name string) (int64, error)
	CreateProjectCost(ctx context.Context, arg CreateProjectCostParams) error
	CreateProjectDetails(ctx context.Context, arg CreateProjectDetailsParams) error
	CreateTimelineEmbedding(ctx context.Context, arg CreateTimelineEmbeddingParams) error
	DeleteLedgerItem(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteTimeline(ctx context.Context, id int64) error
	DeleteTimelineEmbedding(ctx context.Context, timelineSemanticDocumentsID *int64) error
	EnsureLedger(ctx context.Context) error
	InsertForegroundProcessMetadata(ctx context.Context, arg InsertForegroundProcessMetadataParams) (int64, error)
	UpsertApplication(ctx context.Context, arg UpsertApplicationParams) (int64, error)
	UpsertApplicationSettings(ctx context.Context, arg UpsertApplicationSettingsParams) error
	UpsertForegroundProcess(ctx context.Context, arg UpsertForegroundProcessParams) (int64, error)
	UpsertTimeline(ctx context.Context, arg UpsertTimelineParams) (int64, error)
	UpsertTimelineSemanticDocument(ctx context.Context, arg UpsertTimelineSemanticDocumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
