// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package writequeries

import (
	"context"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSemanticDocumentEmbedding(ctx context.Context, arg CreateSemanticDocumentEmbeddingParams) error
	CreateTimesheetEntry(ctx context.Context, arg CreateTimesheetEntryParams) (TimesheetEntry, error)
	CreateTimesheetEntryUsageBlock(ctx context.Context, arg CreateTimesheetEntryUsageBlockParams) error
	CreateTransitionEvent(ctx context.Context, arg CreateTransitionEventParams) (int64, error)
	CreateTransitionEventMetadata(ctx context.Context, arg CreateTransitionEventMetadataParams) error
	CreateTransitionEventNow(ctx context.Context, arg CreateTransitionEventNowParams) (int64, error)
	DeleteProject(ctx context.Context, id string) error
	DeleteSemanticDocumentEmbedding(ctx context.Context, semanticDocumentID int64) error
	DeleteTimesheetEntry(ctx context.Context, id string) error
	EnsureTimesheet(ctx context.Context, arg EnsureTimesheetParams) (Timesheet, error)
	UpsertAISettings(ctx context.Context, arg UpsertAISettingsParams) error
	UpsertApplication(ctx context.Context, arg UpsertApplicationParams) (int64, error)
	UpsertSemanticDocument(ctx context.Context, arg UpsertSemanticDocumentParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
