// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timesheets.sql

package writequeries

import (
	"context"
	"database/sql"
)

const createLedgerItem = `-- name: CreateLedgerItem :one
INSERT INTO ledger_items (ledger_id, billable, title, notes, started_at_utc, ended_at_utc)
VALUES (1, ?, ?, ?, ?, ?)
RETURNING
  id,
  ledger_id,
  billable,
  title,
  notes,
  started_at_utc,
  ended_at_utc
`

type CreateLedgerItemParams struct {
	Billable     bool
	Title        string
	Notes        sql.NullString
	StartedAtUtc sql.NullTime
	EndedAtUtc   sql.NullTime
}

func (q *Queries) CreateLedgerItem(ctx context.Context, arg CreateLedgerItemParams) (LedgerItem, error) {
	row := q.db.QueryRowContext(ctx, createLedgerItem,
		arg.Billable,
		arg.Title,
		arg.Notes,
		arg.StartedAtUtc,
		arg.EndedAtUtc,
	)
	var i LedgerItem
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Billable,
		&i.Title,
		&i.Notes,
		&i.StartedAtUtc,
		&i.EndedAtUtc,
	)
	return i, err
}

const createLedgerItemTimelineEntry = `-- name: CreateLedgerItemTimelineEntry :exec
INSERT INTO ledger_item_timeline_entries (ledger_items_id, timeline_id)
VALUES (?, ?)
`

type CreateLedgerItemTimelineEntryParams struct {
	LedgerItemsID sql.NullInt64
	TimelineID    sql.NullInt64
}

func (q *Queries) CreateLedgerItemTimelineEntry(ctx context.Context, arg CreateLedgerItemTimelineEntryParams) error {
	_, err := q.db.ExecContext(ctx, createLedgerItemTimelineEntry, arg.LedgerItemsID, arg.TimelineID)
	return err
}

const createProjectCost = `-- name: CreateProjectCost :exec
INSERT INTO project_costs (ledger_items_id, projects_id, costing_type_id, rate)
VALUES (?, ?, ?, ?)
`

type CreateProjectCostParams struct {
	LedgerItemsID sql.NullInt64
	ProjectsID    sql.NullInt64
	CostingTypeID sql.NullInt64
	Rate          sql.NullInt64
}

func (q *Queries) CreateProjectCost(ctx context.Context, arg CreateProjectCostParams) error {
	_, err := q.db.ExecContext(ctx, createProjectCost,
		arg.LedgerItemsID,
		arg.ProjectsID,
		arg.CostingTypeID,
		arg.Rate,
	)
	return err
}

const deleteLedgerItem = `-- name: DeleteLedgerItem :exec
DELETE FROM ledger_items WHERE id = ?
`

func (q *Queries) DeleteLedgerItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLedgerItem, id)
	return err
}

const ensureLedger = `-- name: EnsureLedger :exec
INSERT INTO ledger (id)
VALUES (1)
ON CONFLICT(id) DO NOTHING
`

func (q *Queries) EnsureLedger(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureLedger)
	return err
}
