// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timesheets.sql

package writequeries

import (
	"context"
	"database/sql"
	"time"
)

const createTimesheetEntry = `-- name: CreateTimesheetEntry :one
INSERT INTO timesheet_entries (
  id,
  timesheet_id,
  project_id,
  title,
  notes,
  start_minute,
  duration_minutes,
  billable,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING
  id,
  timesheet_id,
  project_id,
  title,
  notes,
  start_minute,
  duration_minutes,
  billable,
  created_at,
  updated_at
`

type CreateTimesheetEntryParams struct {
	ID              string
	TimesheetID     string
	ProjectID       sql.NullString
	Title           string
	Notes           string
	StartMinute     int64
	DurationMinutes int64
	Billable        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateTimesheetEntry(ctx context.Context, arg CreateTimesheetEntryParams) (TimesheetEntry, error) {
	row := q.db.QueryRowContext(ctx, createTimesheetEntry,
		arg.ID,
		arg.TimesheetID,
		arg.ProjectID,
		arg.Title,
		arg.Notes,
		arg.StartMinute,
		arg.DurationMinutes,
		arg.Billable,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TimesheetEntry
	err := row.Scan(
		&i.ID,
		&i.TimesheetID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.StartMinute,
		&i.DurationMinutes,
		&i.Billable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimesheetEntryUsageBlock = `-- name: CreateTimesheetEntryUsageBlock :exec
INSERT INTO timesheet_entry_usage_blocks (
  timesheet_entry_id,
  usage_id,
  sort_order
)
VALUES (?, ?, ?)
`

type CreateTimesheetEntryUsageBlockParams struct {
	TimesheetEntryID string
	UsageID          string
	SortOrder        int64
}

func (q *Queries) CreateTimesheetEntryUsageBlock(ctx context.Context, arg CreateTimesheetEntryUsageBlockParams) error {
	_, err := q.db.ExecContext(ctx, createTimesheetEntryUsageBlock, arg.TimesheetEntryID, arg.UsageID, arg.SortOrder)
	return err
}

const deleteTimesheetEntry = `-- name: DeleteTimesheetEntry :exec
DELETE FROM timesheet_entries
WHERE id = ?
`

func (q *Queries) DeleteTimesheetEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTimesheetEntry, id)
	return err
}

const ensureTimesheet = `-- name: EnsureTimesheet :one
INSERT INTO timesheets (
  id,
  started_at,
  ended_at,
  created_at,
  updated_at
)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (started_at, ended_at) DO UPDATE SET updated_at = timesheets.updated_at
RETURNING
  id,
  started_at,
  ended_at,
  created_at,
  updated_at
`

type EnsureTimesheetParams struct {
	ID        string
	StartedAt time.Time
	EndedAt   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) EnsureTimesheet(ctx context.Context, arg EnsureTimesheetParams) (Timesheet, error) {
	row := q.db.QueryRowContext(ctx, ensureTimesheet,
		arg.ID,
		arg.StartedAt,
		arg.EndedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Timesheet
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
