// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_timeline_end.sql

package writequeries

import (
	"context"
	"database/sql"
)

const updateTimelineEnd = `-- name: UpdateTimelineEnd :exec
UPDATE timeline SET end_foreground_process_id = ? WHERE id = ?
`

type UpdateTimelineEndParams struct {
	EndForegroundProcessID sql.NullInt64
	ID                     int64
}

func (q *Queries) UpdateTimelineEnd(ctx context.Context, arg UpdateTimelineEndParams) error {
	_, err := q.db.ExecContext(ctx, updateTimelineEnd, arg.EndForegroundProcessID, arg.ID)
	return err
}
