// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_masked_value.sql

package writequeries

import (
	"context"
)

const upsertMaskedValue = `-- name: UpsertMaskedValue :one
INSERT INTO masked_values (masking_category, value, masked_value)
VALUES (?, ?, ?)
ON CONFLICT(masking_category, value) DO UPDATE SET
    value = excluded.value
RETURNING masked_value
`

type UpsertMaskedValueParams struct {
	MaskingCategory string
	Value           string
	MaskedValue     string
}

func (q *Queries) UpsertMaskedValue(ctx context.Context, arg UpsertMaskedValueParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertMaskedValue, arg.MaskingCategory, arg.Value, arg.MaskedValue)
	var masked_value string
	err := row.Scan(&masked_value)
	return masked_value, err
}
