// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_foreground_process.sql

package writequeries

import (
	"context"
	"time"
)

const upsertForegroundProcess = `-- name: UpsertForegroundProcess :one
INSERT INTO foreground_processes(application_id, pid, created_at_utc)
VALUES (?, ?, ?)
ON CONFLICT(created_at_utc) DO UPDATE SET
    application_id = excluded.application_id,
    pid = excluded.pid
RETURNING id
`

type UpsertForegroundProcessParams struct {
	ApplicationID *int64
	Pid           int64
	CreatedAtUtc  time.Time
}

func (q *Queries) UpsertForegroundProcess(ctx context.Context, arg UpsertForegroundProcessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertForegroundProcess, arg.ApplicationID, arg.Pid, arg.CreatedAtUtc)
	var id int64
	err := row.Scan(&id)
	return id, err
}
