// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_application_category_map.sql

package writequeries

import (
	"context"
)

const upsertApplicationCategoryMap = `-- name: UpsertApplicationCategoryMap :exec
INSERT INTO application_application_categories_map (application_id, application_categories_id)
VALUES (?, ?)
ON CONFLICT(application_id, application_categories_id) DO NOTHING
`

type UpsertApplicationCategoryMapParams struct {
	ApplicationID           int64
	ApplicationCategoriesID int64
}

func (q *Queries) UpsertApplicationCategoryMap(ctx context.Context, arg UpsertApplicationCategoryMapParams) error {
	_, err := q.db.ExecContext(ctx, upsertApplicationCategoryMap, arg.ApplicationID, arg.ApplicationCategoriesID)
	return err
}
