// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_semantic_document.sql

package writequeries

import (
	"context"
	"database/sql"
)

const upsertSemanticDocument = `-- name: UpsertSemanticDocument :one
INSERT INTO semantic_documents (
  document_key,
  document_type,
  transition_event_id,
  started_at,
  ended_at,
  content
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(document_key) DO UPDATE SET
  document_type = excluded.document_type,
  transition_event_id = excluded.transition_event_id,
  started_at = excluded.started_at,
  ended_at = excluded.ended_at,
  content = excluded.content
RETURNING id
`

type UpsertSemanticDocumentParams struct {
	DocumentKey       string
	DocumentType      string
	TransitionEventID sql.NullInt64
	StartedAt         sql.NullTime
	EndedAt           sql.NullTime
	Content           string
}

func (q *Queries) UpsertSemanticDocument(ctx context.Context, arg UpsertSemanticDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertSemanticDocument,
		arg.DocumentKey,
		arg.DocumentType,
		arg.TransitionEventID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Content,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
