// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_timeline.sql

package writequeries

import (
	"context"
)

const upsertTimeline = `-- name: UpsertTimeline :one
INSERT INTO timeline(initial_foreground_process_id, end_foreground_process_id)
VALUES (
    -- the fallback is the observation before the one just written. it orders by id rather than by
    -- created_at_utc because ids are handed out in observation order, while the timestamp is text
    -- carrying whatever offset the observation was recorded in and does not sort chronologically
    -- across offsets
    COALESCE(CAST(?1 AS INTEGER), (SELECT id FROM foreground_processes ORDER BY id DESC LIMIT 1 OFFSET 1)),
    ?2
)
ON CONFLICT(initial_foreground_process_id) DO UPDATE SET
    end_foreground_process_id = excluded.end_foreground_process_id
RETURNING id
`

type UpsertTimelineParams struct {
	InitialForegroundProcessID *int64
	EndForegroundProcessID     *int64
}

func (q *Queries) UpsertTimeline(ctx context.Context, arg UpsertTimelineParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTimeline, arg.InitialForegroundProcessID, arg.EndForegroundProcessID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
