// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_timeline_semantic_document.sql

package writequeries

import (
	"context"
	"database/sql"
)

const upsertTimelineSemanticDocument = `-- name: UpsertTimelineSemanticDocument :one
INSERT INTO timeline_semantic_documents (document_key, timeline_id, type, content)
VALUES (?, ?, ?, ?)
ON CONFLICT(document_key) DO UPDATE SET
  timeline_id = excluded.timeline_id,
  type = excluded.type,
  content = excluded.content
RETURNING id
`

type UpsertTimelineSemanticDocumentParams struct {
	DocumentKey string
	TimelineID  sql.NullInt64
	Type        sql.NullInt64
	Content     string
}

func (q *Queries) UpsertTimelineSemanticDocument(ctx context.Context, arg UpsertTimelineSemanticDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTimelineSemanticDocument,
		arg.DocumentKey,
		arg.TimelineID,
		arg.Type,
		arg.Content,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
