// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_application_category.sql

package writequeries

import (
	"context"
)

const upsertApplicationCategory = `-- name: UpsertApplicationCategory :one
INSERT INTO application_categories (category_id, code, label)
VALUES (?, ?, ?)
ON CONFLICT(category_id) DO UPDATE SET
  code = excluded.code,
  label = excluded.label
RETURNING id
`

type UpsertApplicationCategoryParams struct {
	CategoryID int64
	Code       string
	Label      string
}

func (q *Queries) UpsertApplicationCategory(ctx context.Context, arg UpsertApplicationCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertApplicationCategory, arg.CategoryID, arg.Code, arg.Label)
	var id int64
	err := row.Scan(&id)
	return id, err
}
