// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_application.sql

package writequeries

import (
	"context"
	"database/sql"
)

const upsertApplication = `-- name: UpsertApplication :one
INSERT INTO applications (name, operating_system_id, path)
VALUES (?1, ?2, ?3)
ON CONFLICT(name) DO UPDATE SET
  name = excluded.name,
  operating_system_id = COALESCE(excluded.operating_system_id, applications.operating_system_id),
  path = COALESCE(excluded.path, applications.path)
RETURNING id
`

type UpsertApplicationParams struct {
	Name              string
	OperatingSystemID sql.NullInt64
	Path              sql.NullString
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertApplication, arg.Name, arg.OperatingSystemID, arg.Path)
	var id int64
	err := row.Scan(&id)
	return id, err
}
