// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_application.sql

package writequeries

import (
	"context"
)

const upsertApplication = `-- name: UpsertApplication :one
INSERT INTO applications (name, identifier, operating_system_id, path)
VALUES (?, ?, ?, ?)
ON CONFLICT(identifier, operating_system_id) DO UPDATE SET
  name = excluded.name,
  path = COALESCE(excluded.path, applications.path)
RETURNING id
`

type UpsertApplicationParams struct {
	Name              string
	Identifier        *string
	OperatingSystemID int64
	Path              *string
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertApplication,
		arg.Name,
		arg.Identifier,
		arg.OperatingSystemID,
		arg.Path,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
