// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_application_settings.sql

package writequeries

import (
	"context"
)

const upsertApplicationSettings = `-- name: UpsertApplicationSettings :exec
INSERT INTO application_settings (
  id,
  model_provider_id,
  model_provider_base_url,
  embedding_model_id,
  semantic_model_id,
  release_channel
)
VALUES (1, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  model_provider_id = excluded.model_provider_id,
  model_provider_base_url = excluded.model_provider_base_url,
  embedding_model_id = excluded.embedding_model_id,
  semantic_model_id = excluded.semantic_model_id,
  release_channel = COALESCE(excluded.release_channel, application_settings.release_channel)
`

type UpsertApplicationSettingsParams struct {
	ModelProviderID      *int64
	ModelProviderBaseUrl *string
	EmbeddingModelID     int64
	SemanticModelID      int64
	ReleaseChannel       *int64
}

func (q *Queries) UpsertApplicationSettings(ctx context.Context, arg UpsertApplicationSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertApplicationSettings,
		arg.ModelProviderID,
		arg.ModelProviderBaseUrl,
		arg.EmbeddingModelID,
		arg.SemanticModelID,
		arg.ReleaseChannel,
	)
	return err
}
