// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_masked_values.sql

package readqueries

import (
	"context"
)

const getMaskedValues = `-- name: GetMaskedValues :many
SELECT
    masked_values.masking_category,
    masked_values.value,
    masked_values.masked_value
FROM masked_values
ORDER BY masked_values.id ASC
`

type GetMaskedValuesRow struct {
	MaskingCategory string
	Value           string
	MaskedValue     string
}

func (q *Queries) GetMaskedValues(ctx context.Context) ([]GetMaskedValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMaskedValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaskedValuesRow
	for rows.Next() {
		var i GetMaskedValuesRow
		if err := rows.Scan(&i.MaskingCategory, &i.Value, &i.MaskedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
