// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_unindexed_foreground_processes.sql

package readqueries

import (
	"context"
	"time"
)

const getUnindexedForegroundProcesses = `-- name: GetUnindexedForegroundProcesses :many
SELECT
    foreground_processes.id,
    applications.name AS application_name,
    applications.identifier AS application_identifier,
    foreground_processes.application_id,
    foreground_processes.pid,
    foreground_processes.created_at_utc,
    foreground_process_metadata.browser,
    foreground_process_metadata.browser_vendor,
    bc.code AS browser_category,
    foreground_process_metadata.idle,
    foreground_process_metadata.killed,
    foreground_process_metadata.tab,
    foreground_process_metadata.cdp_url,
    foreground_process_metadata.latitude,
    foreground_process_metadata.longitude,
    foreground_process_metadata.public_ip,
    foreground_process_metadata.title_source,
    foreground_process_metadata.window_title
FROM foreground_processes
JOIN applications ON applications.id = foreground_processes.application_id
JOIN foreground_process_metadata ON foreground_process_metadata.foreground_process_id = foreground_processes.id
LEFT JOIN application_categories bc ON bc.id = foreground_process_metadata.browser_category
WHERE       foreground_processes.id NOT IN (SELECT timeline.initial_foreground_process_id AS foreground_process_id
                                          FROM timeline
                                          JOIN timeline_semantic_documents ON timeline_semantic_documents.timeline_id = timeline.id
                                          WHERE timeline.initial_foreground_process_id IS NOT NULL
                                          UNION ALL
                                          SELECT timeline.end_foreground_process_id AS foreground_process_id
                                          FROM timeline
                                          JOIN timeline_semantic_documents ON timeline_semantic_documents.timeline_id = timeline.id
                                          WHERE timeline.end_foreground_process_id IS NOT NULL)
      AND   foreground_processes.id > ?1
ORDER BY foreground_processes.id ASC
LIMIT ?2
`

type GetUnindexedForegroundProcessesParams struct {
	ForegroundProcessId int64
	PageSize            int64
}

type GetUnindexedForegroundProcessesRow struct {
	ID                    int64
	ApplicationName       string
	ApplicationIdentifier *string
	ApplicationID         *int64
	Pid                   *int64
	CreatedAtUtc          time.Time
	Browser               bool
	BrowserVendor         *string
	BrowserCategory       *string
	Idle                  bool
	Killed                bool
	Tab                   *string
	CdpUrl                *string
	Latitude              *float64
	Longitude             *float64
	PublicIp              *string
	TitleSource           *string
	WindowTitle           *string
}

func (q *Queries) GetUnindexedForegroundProcesses(ctx context.Context, arg GetUnindexedForegroundProcessesParams) ([]GetUnindexedForegroundProcessesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnindexedForegroundProcesses, arg.ForegroundProcessId, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnindexedForegroundProcessesRow
	for rows.Next() {
		var i GetUnindexedForegroundProcessesRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationName,
			&i.ApplicationIdentifier,
			&i.ApplicationID,
			&i.Pid,
			&i.CreatedAtUtc,
			&i.Browser,
			&i.BrowserVendor,
			&i.BrowserCategory,
			&i.Idle,
			&i.Killed,
			&i.Tab,
			&i.CdpUrl,
			&i.Latitude,
			&i.Longitude,
			&i.PublicIp,
			&i.TitleSource,
			&i.WindowTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
