// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_latest_timeline_entry.sql

package readqueries

import (
	"context"
	"time"
)

const getLatestTimelineEntry = `-- name: GetLatestTimelineEntry :one
SELECT
  timeline.id AS timeline_id,
  timeline.initial_foreground_process_id,
  timeline.end_foreground_process_id,
  fp0.pid AS initial_pid,
  fp0.created_at_utc AS initial_created_at,
  foreground_process_metadata.tab AS initial_tab,
  foreground_process_metadata.idle AS initial_idle
FROM timeline
JOIN foreground_processes fp0 ON fp0.id = timeline.initial_foreground_process_id
LEFT JOIN foreground_process_metadata ON foreground_process_metadata.foreground_process_id = fp0.id
ORDER BY timeline.id DESC
LIMIT 1
`

type GetLatestTimelineEntryRow struct {
	TimelineID                 int64
	InitialForegroundProcessID *int64
	EndForegroundProcessID     *int64
	InitialPid                 int64
	InitialCreatedAt           time.Time
	InitialTab                 *string
	InitialIdle                *bool
}

func (q *Queries) GetLatestTimelineEntry(ctx context.Context) (GetLatestTimelineEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestTimelineEntry)
	var i GetLatestTimelineEntryRow
	err := row.Scan(
		&i.TimelineID,
		&i.InitialForegroundProcessID,
		&i.EndForegroundProcessID,
		&i.InitialPid,
		&i.InitialCreatedAt,
		&i.InitialTab,
		&i.InitialIdle,
	)
	return i, err
}
