// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_transition_event.sql

package readqueries

import (
	"context"
	"database/sql"
	"time"
)

const getTransitionEvent = `-- name: GetTransitionEvent :one
SELECT
  transition_events.id AS transition_event_id,
  applications.name AS application_name,
  applications.platform_identifier AS application_platform_identifier,
  applications.path AS application_path,
  transition_event_reasons.reason AS reason,
  transition_events.started_at,
  transition_events.ended_at,
  transition_event_metadata.browser,
  transition_event_metadata.tab,
  transition_event_metadata.idle,
  transition_event_metadata.cdp_url,
  transition_event_metadata.pid
FROM transition_events
JOIN transition_event_reasons ON transition_event_reasons.id = transition_events.transition_reason_id
LEFT JOIN applications ON applications.id = transition_events.application_id
LEFT JOIN transition_event_metadata ON transition_event_metadata.transition_event_id = transition_events.id
WHERE transition_events.id = ?
`

type GetTransitionEventRow struct {
	TransitionEventID             int64
	ApplicationName               sql.NullString
	ApplicationPlatformIdentifier sql.NullString
	ApplicationPath               sql.NullString
	Reason                        string
	StartedAt                     time.Time
	EndedAt                       time.Time
	Browser                       sql.NullBool
	Tab                           *string
	Idle                          sql.NullBool
	CdpUrl                        *string
	Pid                           sql.NullInt64
}

func (q *Queries) GetTransitionEvent(ctx context.Context, id int64) (GetTransitionEventRow, error) {
	row := q.db.QueryRowContext(ctx, getTransitionEvent, id)
	var i GetTransitionEventRow
	err := row.Scan(
		&i.TransitionEventID,
		&i.ApplicationName,
		&i.ApplicationPlatformIdentifier,
		&i.ApplicationPath,
		&i.Reason,
		&i.StartedAt,
		&i.EndedAt,
		&i.Browser,
		&i.Tab,
		&i.Idle,
		&i.CdpUrl,
		&i.Pid,
	)
	return i, err
}
