// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_masked_categories.sql

package readqueries

import (
	"context"
)

const getMaskedCategories = `-- name: GetMaskedCategories :many
SELECT
    source.category_id AS category_id,
    target.category_id AS masked_category_id
FROM masked_categories
JOIN application_categories AS source
    ON source.id = masked_categories.application_categories_id
JOIN application_categories AS target
    ON target.id = masked_categories.masked_application_categories_id
ORDER BY source.category_id ASC
`

type GetMaskedCategoriesRow struct {
	CategoryID       int64
	MaskedCategoryID int64
}

func (q *Queries) GetMaskedCategories(ctx context.Context) ([]GetMaskedCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMaskedCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaskedCategoriesRow
	for rows.Next() {
		var i GetMaskedCategoriesRow
		if err := rows.Scan(&i.CategoryID, &i.MaskedCategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
