// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_semantic_event_document_source.sql

package readqueries

import (
	"context"
	"time"
)

const getSemanticEventDocumentSource = `-- name: GetSemanticEventDocumentSource :one
SELECT
  timeline.id AS transition_event_id,
  applications.name AS application_name,
  fp0.application_id AS application_id,
  fp0.created_at_utc AS started_at,
  fp1.created_at_utc AS ended_at,
  foreground_process_metadata.browser,
  foreground_process_metadata.tab,
  foreground_process_metadata.idle,
  foreground_process_metadata.cdp_url,
  (
    SELECT pfp.application_id
    FROM timeline pt
    JOIN foreground_processes pfp ON pfp.id = pt.initial_foreground_process_id
    WHERE pt.id < timeline.id
    ORDER BY pt.id DESC
    LIMIT 1
  ) AS prev_application_id,
  (
    SELECT pmeta.idle
    FROM timeline pt
    LEFT JOIN foreground_process_metadata pmeta ON pmeta.foreground_process_id = pt.initial_foreground_process_id
    WHERE pt.id < timeline.id
    ORDER BY pt.id DESC
    LIMIT 1
  ) AS prev_idle
FROM timeline
JOIN foreground_processes fp0 ON fp0.id = timeline.initial_foreground_process_id
JOIN foreground_processes fp1 ON fp1.id = timeline.end_foreground_process_id
LEFT JOIN applications ON applications.id = fp0.application_id
LEFT JOIN foreground_process_metadata ON foreground_process_metadata.foreground_process_id = fp0.id
WHERE timeline.id = ?
`

type GetSemanticEventDocumentSourceRow struct {
	TransitionEventID int64
	ApplicationName   *string
	ApplicationID     *int64
	StartedAt         time.Time
	EndedAt           time.Time
	Browser           *bool
	Tab               *string
	Idle              *bool
	CdpUrl            *string
	PrevApplicationID *int64
	PrevIdle          *bool
}

func (q *Queries) GetSemanticEventDocumentSource(ctx context.Context, id int64) (GetSemanticEventDocumentSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getSemanticEventDocumentSource, id)
	var i GetSemanticEventDocumentSourceRow
	err := row.Scan(
		&i.TransitionEventID,
		&i.ApplicationName,
		&i.ApplicationID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Browser,
		&i.Tab,
		&i.Idle,
		&i.CdpUrl,
		&i.PrevApplicationID,
		&i.PrevIdle,
	)
	return i, err
}
