// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_unenriched_foreground_processes.sql

package readqueries

import (
	"context"
	"time"
)

const getUnenrichedForegroundProcesses = `-- name: GetUnenrichedForegroundProcesses :many
SELECT
    foreground_processes.id,
    applications.name AS application_name,
    applications.identifier AS application_identifier,
    foreground_processes.application_id,
    foreground_processes.pid,
    foreground_processes.created_at_utc,
    foreground_process_metadata.browser,
    foreground_process_metadata.browser_vendor,
    bc.code AS browser_category,
    foreground_process_metadata.idle,
    foreground_process_metadata.killed,
    foreground_process_metadata.tab,
    foreground_process_metadata.cdp_url,
    foreground_process_metadata.latitude,
    foreground_process_metadata.longitude,
    foreground_process_metadata.public_ip,
    foreground_process_metadata.title_source,
    foreground_process_metadata.window_title
FROM foreground_processes
JOIN applications ON applications.id = foreground_processes.application_id
LEFT JOIN application_categories bc ON bc.id = foreground_process_metadata.browser_category
JOIN foreground_process_metadata ON foreground_process_metadata.foreground_process_id = foreground_processes.id
WHERE  ((foreground_process_metadata.tab IS NULL AND foreground_process_metadata.browser = 1)
    OR (    foreground_process_metadata.latitude IS NULL
        AND foreground_process_metadata.longitude IS NULL
        AND foreground_process_metadata.public_ip IS NOT NULL))
    AND foreground_processes.id > ?1
ORDER BY foreground_processes.id ASC
LIMIT ?2
`

type GetUnenrichedForegroundProcessesParams struct {
	ForegroundProcessId int64
	PageSize            int64
}

type GetUnenrichedForegroundProcessesRow struct {
	ID                    int64
	ApplicationName       string
	ApplicationIdentifier *string
	ApplicationID         *int64
	Pid                   *int64
	CreatedAtUtc          time.Time
	Browser               bool
	BrowserVendor         *string
	BrowserCategory       string
	Idle                  bool
	Killed                bool
	Tab                   *string
	CdpUrl                *string
	Latitude              *float64
	Longitude             *float64
	PublicIp              *string
	TitleSource           *string
	WindowTitle           *string
}

func (q *Queries) GetUnenrichedForegroundProcesses(ctx context.Context, arg GetUnenrichedForegroundProcessesParams) ([]GetUnenrichedForegroundProcessesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnenrichedForegroundProcesses, arg.ForegroundProcessId, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnenrichedForegroundProcessesRow
	for rows.Next() {
		var i GetUnenrichedForegroundProcessesRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationName,
			&i.ApplicationIdentifier,
			&i.ApplicationID,
			&i.Pid,
			&i.CreatedAtUtc,
			&i.Browser,
			&i.BrowserVendor,
			&i.BrowserCategory,
			&i.Idle,
			&i.Killed,
			&i.Tab,
			&i.CdpUrl,
			&i.Latitude,
			&i.Longitude,
			&i.PublicIp,
			&i.TitleSource,
			&i.WindowTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
