// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_application_settings.sql

package readqueries

import (
	"context"
)

const getApplicationSettings = `-- name: GetApplicationSettings :one
SELECT
  application_settings.id,
  application_settings.model_provider_id,
  model_providers.label AS model_provider_label,
  application_settings.model_provider_base_url,
  application_settings.embedding_model_id,
  application_settings.semantic_model_id,
  application_settings.release_channel,
  embedding_models.openrouter_slug AS embedding_openrouter_slug,
  embedding_models.ollama_slug AS embedding_ollama_slug,
  embedding_models.label AS embedding_label,
  semantic_models.openrouter_slug AS semantic_openrouter_slug,
  semantic_models.ollama_slug AS semantic_ollama_slug,
  semantic_models.label AS semantic_label
FROM application_settings
LEFT JOIN model_providers ON model_providers.id = application_settings.model_provider_id
JOIN models AS embedding_models ON embedding_models.id = application_settings.embedding_model_id
JOIN models AS semantic_models ON semantic_models.id = application_settings.semantic_model_id
WHERE application_settings.id = 1
`

type GetApplicationSettingsRow struct {
	ID                      int64
	ModelProviderID         *int64
	ModelProviderLabel      string
	ModelProviderBaseUrl    *string
	EmbeddingModelID        int64
	SemanticModelID         int64
	ReleaseChannel          *int64
	EmbeddingOpenrouterSlug *string
	EmbeddingOllamaSlug     *string
	EmbeddingLabel          string
	SemanticOpenrouterSlug  *string
	SemanticOllamaSlug      *string
	SemanticLabel           string
}

func (q *Queries) GetApplicationSettings(ctx context.Context) (GetApplicationSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getApplicationSettings)
	var i GetApplicationSettingsRow
	err := row.Scan(
		&i.ID,
		&i.ModelProviderID,
		&i.ModelProviderLabel,
		&i.ModelProviderBaseUrl,
		&i.EmbeddingModelID,
		&i.SemanticModelID,
		&i.ReleaseChannel,
		&i.EmbeddingOpenrouterSlug,
		&i.EmbeddingOllamaSlug,
		&i.EmbeddingLabel,
		&i.SemanticOpenrouterSlug,
		&i.SemanticOllamaSlug,
		&i.SemanticLabel,
	)
	return i, err
}
