// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_semantic_event_document_source.sql

package readqueries

import (
	"context"
	"database/sql"
	"time"
)

const getSemanticEventDocumentSource = `-- name: GetSemanticEventDocumentSource :one
SELECT
  transition_events.id AS transition_event_id,
  applications.name AS application_name,
  transition_event_reasons.reason AS reason,
  transition_events.started_at,
  transition_events.ended_at,
  transition_event_metadata.browser,
  transition_event_metadata.tab,
  transition_event_metadata.idle,
  transition_event_metadata.cdp_url
FROM transition_events
JOIN transition_event_reasons ON transition_event_reasons.id = transition_events.transition_reason_id
LEFT JOIN applications ON applications.id = transition_events.application_id
LEFT JOIN transition_event_metadata ON transition_event_metadata.transition_event_id = transition_events.id
WHERE transition_events.id = ?
`

type GetSemanticEventDocumentSourceRow struct {
	TransitionEventID int64
	ApplicationName   sql.NullString
	Reason            string
	StartedAt         time.Time
	EndedAt           time.Time
	Browser           sql.NullBool
	Tab               *string
	Idle              sql.NullBool
	CdpUrl            *string
}

func (q *Queries) GetSemanticEventDocumentSource(ctx context.Context, id int64) (GetSemanticEventDocumentSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getSemanticEventDocumentSource, id)
	var i GetSemanticEventDocumentSourceRow
	err := row.Scan(
		&i.TransitionEventID,
		&i.ApplicationName,
		&i.Reason,
		&i.StartedAt,
		&i.EndedAt,
		&i.Browser,
		&i.Tab,
		&i.Idle,
		&i.CdpUrl,
	)
	return i, err
}
