// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_transition_events.sql

package readqueries

import (
	"context"
	"database/sql"
	"time"
)

const getTransitionEvents = `-- name: GetTransitionEvents :many
SELECT
  timeline.id AS transition_event_id,
  applications.name AS application_name,
  applications.identifier AS application_identifier,
  applications.path AS application_path,
  fp0.created_at_utc AS started_at,
  fp1.created_at_utc AS ended_at,
  foreground_process_metadata.browser,
  foreground_process_metadata.tab,
  foreground_process_metadata.idle,
  foreground_process_metadata.cdp_url,
  fp0.application_id,
  fp0.pid
FROM timeline
JOIN foreground_processes fp0 ON fp0.id = timeline.initial_foreground_process_id
JOIN foreground_processes fp1 ON fp1.id = timeline.end_foreground_process_id
LEFT JOIN applications ON applications.id = fp0.application_id
LEFT JOIN foreground_process_metadata ON foreground_process_metadata.foreground_process_id = fp0.id
WHERE (?1 IS NULL OR fp0.created_at_utc >= ?1)
  AND (?2 IS NULL OR fp1.created_at_utc <= ?2)
ORDER BY fp0.created_at_utc ASC, timeline.id ASC
`

type GetTransitionEventsParams struct {
	StartedAt interface{}
	EndedAt   interface{}
}

type GetTransitionEventsRow struct {
	TransitionEventID     int64
	ApplicationName       sql.NullString
	ApplicationIdentifier sql.NullString
	ApplicationPath       sql.NullString
	StartedAt             time.Time
	EndedAt               time.Time
	Browser               sql.NullBool
	Tab                   *string
	Idle                  sql.NullBool
	CdpUrl                *string
	ApplicationID         sql.NullInt64
	Pid                   int64
}

func (q *Queries) GetTransitionEvents(ctx context.Context, arg GetTransitionEventsParams) ([]GetTransitionEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransitionEvents, arg.StartedAt, arg.EndedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransitionEventsRow
	for rows.Next() {
		var i GetTransitionEventsRow
		if err := rows.Scan(
			&i.TransitionEventID,
			&i.ApplicationName,
			&i.ApplicationIdentifier,
			&i.ApplicationPath,
			&i.StartedAt,
			&i.EndedAt,
			&i.Browser,
			&i.Tab,
			&i.Idle,
			&i.CdpUrl,
			&i.ApplicationID,
			&i.Pid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
