// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_timeline.sql

package readqueries

import (
	"context"
	"time"
)

const getTimeline = `-- name: GetTimeline :many
SELECT
    timeline.id,
    -- initial
    timeline.initial_foreground_process_id AS initial_fp_id,
    initial_app.name AS initial_application_name,
    initial_app.identifier AS initial_application_identifier,
    initial_app.path AS initial_application_path,
    -- the application's category is not selected here: it maps to categories many-to-many, so a
    -- join would fan this row out into one duplicate per classification. GetApplicationCategories
    -- resolves it per application, keyed off the application_id above
    initial.application_id AS initial_application_id,
    initial.pid AS initial_pid,
    initial.created_at_utc AS initial_created_at_utc,
    initial_fpm.browser AS initial_browser,
    initial_fpm.browser_vendor AS initial_browser_vendor,
    initial_bc.code AS initial_browser_category,
    initial_fpm.idle AS initial_idle,
    initial_fpm.killed AS initial_killed,
    initial_fpm.tab AS initial_tab,
    initial_fpm.cdp_url AS initial_cdp_url,
    initial_fpm.latitude AS initial_latitude,
    initial_fpm.longitude AS initial_longitude,
    initial_fpm.public_ip AS initial_public_ip,
    initial_fpm.title_source AS initial_title_source,
    initial_fpm.window_title AS initial_window_title,
    -- final
    timeline.end_foreground_process_id AS final_fp_id,
    final_app.name AS final_application_name,
    final_app.identifier AS final_application_identifier,
    final_app.path AS final_application_path,
    final.application_id AS final_application_id,
    final.pid AS final_pid,
    final.created_at_utc AS final_created_at_utc,
    final_fpm.browser AS final_browser,
    final_fpm.browser_vendor AS final_browser_vendor,
    final_bc.code AS final_browser_category,
    final_fpm.idle AS final_idle,
    final_fpm.killed AS final_killed,
    final_fpm.tab AS final_tab,
    final_fpm.cdp_url AS final_cdp_url,
    final_fpm.latitude AS final_latitude,
    final_fpm.longitude AS final_longitude,
    final_fpm.public_ip AS final_public_ip,
    final_fpm.title_source AS final_title_source,
    final_fpm.window_title AS final_window_title
FROM timeline
LEFT JOIN foreground_processes initial ON initial.id = timeline.initial_foreground_process_id
LEFT JOIN foreground_processes final ON final.id = timeline.end_foreground_process_id -- absent until the entry is closed
LEFT JOIN foreground_process_metadata initial_fpm ON initial_fpm.foreground_process_id = initial.id
LEFT JOIN foreground_process_metadata final_fpm ON final_fpm.foreground_process_id = final.id
LEFT JOIN applications initial_app ON initial_app.id = initial.application_id -- an idle observation has no application
LEFT JOIN applications final_app ON final_app.id = final.application_id
LEFT JOIN application_categories initial_bc ON initial_bc.id = initial_fpm.browser_category -- only browsers are categorized
LEFT JOIN application_categories final_bc ON final_bc.id = final_fpm.browser_category
WHERE   timeline.id > ?1
    AND timeline.initial_foreground_process_id IS NOT NULL
    -- an open entry is never too short to report: it is still running. the floor is a parameter
    -- because it breaks the entry chain (row N's final observation is row N+1's initial one), so
    -- callers that derive durations from adjacency must pass 0
    AND (   timeline.end_foreground_process_id IS NULL
        OR  unixepoch(final.created_at_utc) - unixepoch(initial.created_at_utc)
                >= CAST(?2 AS INTEGER)
        )
    -- half-open, strict: an entry overlaps the window when it ends after the window opens and
    -- starts before it closes. an open entry has not ended, so it always passes the lower bound.
    --
    -- both sides go through unixepoch() because the two are not comparable as text: created_at_utc
    -- is stored with whatever offset the observation carried, while the bounds arrive normalised to
    -- UTC, so a text comparison compares wall clocks rather than instants. unixepoch() also spans
    -- the column's other stored format, the schema default's %Y-%m-%dT%H:%M:%fZ. it truncates to
    -- milliseconds, which is far below the observation interval.
    --
    -- the CAST(... AS TIMESTAMP) guards are only a null test and a type anchor for sqlc: sqlite has
    -- no TIMESTAMP type, so the cast is NUMERIC affinity and mangles the value: it must never wrap
    -- one that is then compared
    AND (   timeline.end_foreground_process_id IS NULL
        OR  (   CAST(?3 AS TIMESTAMP) IS NULL
            OR  unixepoch(final.created_at_utc, 'subsec')
                    > unixepoch(?3, 'subsec'))
        )
    AND (   CAST(?4 AS TIMESTAMP) IS NULL
        OR  unixepoch(initial.created_at_utc, 'subsec')
                < unixepoch(?4, 'subsec'))
ORDER BY timeline.id ASC
LIMIT ?5
`

type GetTimelineParams struct {
	TimelineId         int64
	MinDurationSeconds int64
	StartedAt          *time.Time
	EndedAt            *time.Time
	PageSize           int64
}

type GetTimelineRow struct {
	ID                           int64
	InitialFpID                  *int64
	InitialApplicationName       *string
	InitialApplicationIdentifier *string
	InitialApplicationPath       *string
	InitialApplicationID         *int64
	InitialPid                   *int64
	InitialCreatedAtUtc          *time.Time
	InitialBrowser               *bool
	InitialBrowserVendor         *string
	InitialBrowserCategory       *string
	InitialIdle                  *bool
	InitialKilled                *bool
	InitialTab                   *string
	InitialCdpUrl                *string
	InitialLatitude              *float64
	InitialLongitude             *float64
	InitialPublicIp              *string
	InitialTitleSource           *string
	InitialWindowTitle           *string
	FinalFpID                    *int64
	FinalApplicationName         *string
	FinalApplicationIdentifier   *string
	FinalApplicationPath         *string
	FinalApplicationID           *int64
	FinalPid                     *int64
	FinalCreatedAtUtc            *time.Time
	FinalBrowser                 *bool
	FinalBrowserVendor           *string
	FinalBrowserCategory         *string
	FinalIdle                    *bool
	FinalKilled                  *bool
	FinalTab                     *string
	FinalCdpUrl                  *string
	FinalLatitude                *float64
	FinalLongitude               *float64
	FinalPublicIp                *string
	FinalTitleSource             *string
	FinalWindowTitle             *string
}

// GetTimeline returns each timeline entry with both of its endpoints side by side, keyset
// paginated on timeline.id. The final side is absent while the entry is still open; closed
// entries shorter than min_duration_seconds are switch noise and are filtered out. started_at
// and ended_at are optional window bounds.
func (q *Queries) GetTimeline(ctx context.Context, arg GetTimelineParams) ([]GetTimelineRow, error) {
	rows, err := q.db.QueryContext(ctx, getTimeline,
		arg.TimelineId,
		arg.MinDurationSeconds,
		arg.StartedAt,
		arg.EndedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimelineRow
	for rows.Next() {
		var i GetTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.InitialFpID,
			&i.InitialApplicationName,
			&i.InitialApplicationIdentifier,
			&i.InitialApplicationPath,
			&i.InitialApplicationID,
			&i.InitialPid,
			&i.InitialCreatedAtUtc,
			&i.InitialBrowser,
			&i.InitialBrowserVendor,
			&i.InitialBrowserCategory,
			&i.InitialIdle,
			&i.InitialKilled,
			&i.InitialTab,
			&i.InitialCdpUrl,
			&i.InitialLatitude,
			&i.InitialLongitude,
			&i.InitialPublicIp,
			&i.InitialTitleSource,
			&i.InitialWindowTitle,
			&i.FinalFpID,
			&i.FinalApplicationName,
			&i.FinalApplicationIdentifier,
			&i.FinalApplicationPath,
			&i.FinalApplicationID,
			&i.FinalPid,
			&i.FinalCreatedAtUtc,
			&i.FinalBrowser,
			&i.FinalBrowserVendor,
			&i.FinalBrowserCategory,
			&i.FinalIdle,
			&i.FinalKilled,
			&i.FinalTab,
			&i.FinalCdpUrl,
			&i.FinalLatitude,
			&i.FinalLongitude,
			&i.FinalPublicIp,
			&i.FinalTitleSource,
			&i.FinalWindowTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
