// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_semantic_index_counts.sql

package readqueries

import (
	"context"
	"database/sql"
)

const getSemanticIndexCounts = `-- name: GetSemanticIndexCounts :one
SELECT
  (SELECT COUNT(*) FROM timeline) AS completed_event_count,
  (
    SELECT COUNT(*)
    FROM timeline_semantic_documents
    WHERE type = 1
  ) AS indexed_event_count,
  (
    SELECT COUNT(*)
    FROM timeline_semantic_documents
    JOIN timeline_embeddings
      ON timeline_embeddings.timeline_semantic_documents_id = timeline_semantic_documents.id
    WHERE timeline_semantic_documents.type = 1
      AND timeline_embeddings.embedding_model_id = ?
  ) AS embedded_event_count
`

type GetSemanticIndexCountsRow struct {
	CompletedEventCount int64
	IndexedEventCount   int64
	EmbeddedEventCount  int64
}

func (q *Queries) GetSemanticIndexCounts(ctx context.Context, embeddingModelID sql.NullInt64) (GetSemanticIndexCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getSemanticIndexCounts, embeddingModelID)
	var i GetSemanticIndexCountsRow
	err := row.Scan(&i.CompletedEventCount, &i.IndexedEventCount, &i.EmbeddedEventCount)
	return i, err
}
