// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_transition_event.sql

package readqueries

import (
	"context"
	"database/sql"
	"time"
)

const getTransitionEvent = `-- name: GetTransitionEvent :one
SELECT
  timeline.id AS transition_event_id,
  applications.name AS application_name,
  applications.path AS application_path,
  fp0.created_at_utc AS started_at,
  fp1.created_at_utc AS ended_at,
  foreground_process_metadata.browser,
  foreground_process_metadata.tab,
  foreground_process_metadata.idle,
  foreground_process_metadata.cdp_url,
  fp0.application_id,
  fp0.pid
FROM timeline
JOIN foreground_processes fp0 ON fp0.id = timeline.initial_foreground_process_id
JOIN foreground_processes fp1 ON fp1.id = timeline.end_foreground_process_id
LEFT JOIN applications ON applications.id = fp0.application_id
LEFT JOIN foreground_process_metadata ON foreground_process_metadata.foreground_process_id = fp0.id
WHERE timeline.id = ?
`

type GetTransitionEventRow struct {
	TransitionEventID int64
	ApplicationName   sql.NullString
	ApplicationPath   sql.NullString
	StartedAt         time.Time
	EndedAt           time.Time
	Browser           sql.NullBool
	Tab               *string
	Idle              sql.NullBool
	CdpUrl            *string
	ApplicationID     sql.NullInt64
	Pid               int64
}

func (q *Queries) GetTransitionEvent(ctx context.Context, id int64) (GetTransitionEventRow, error) {
	row := q.db.QueryRowContext(ctx, getTransitionEvent, id)
	var i GetTransitionEventRow
	err := row.Scan(
		&i.TransitionEventID,
		&i.ApplicationName,
		&i.ApplicationPath,
		&i.StartedAt,
		&i.EndedAt,
		&i.Browser,
		&i.Tab,
		&i.Idle,
		&i.CdpUrl,
		&i.ApplicationID,
		&i.Pid,
	)
	return i, err
}
