// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_application_category_codes.sql

package readqueries

import (
	"context"
)

const getApplicationCategoryCodes = `-- name: GetApplicationCategoryCodes :many
SELECT
    application_categories.category_id,
    application_categories.code
FROM application_categories
ORDER BY application_categories.category_id ASC
`

type GetApplicationCategoryCodesRow struct {
	CategoryID int64
	Code       string
}

func (q *Queries) GetApplicationCategoryCodes(ctx context.Context) ([]GetApplicationCategoryCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getApplicationCategoryCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationCategoryCodesRow
	for rows.Next() {
		var i GetApplicationCategoryCodesRow
		if err := rows.Scan(&i.CategoryID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
