// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_application_categories.sql

package readqueries

import (
	"context"
	"strings"
)

const getApplicationCategories = `-- name: GetApplicationCategories :many
SELECT
    application_application_categories_map.application_id,
    application_categories.code
FROM application_application_categories_map
JOIN application_categories
    ON application_categories.id = application_application_categories_map.application_categories_id
WHERE application_application_categories_map.application_id IN (/*SLICE:applicationIds*/?)
ORDER BY
    application_application_categories_map.application_id ASC,
    application_categories.id ASC
`

type GetApplicationCategoriesRow struct {
	ApplicationID int64
	Code          string
}

// GetApplicationCategories returns the taxonomy codes each of the given applications is classified
// under, grouped by application and lowest surrogate id first. An application maps to categories
// many-to-many, but ingest links exactly one today, so callers read the first. An application with
// no classification yields no rows rather than a null one.
func (q *Queries) GetApplicationCategories(ctx context.Context, applicationids []int64) ([]GetApplicationCategoriesRow, error) {
	query := getApplicationCategories
	var queryParams []interface{}
	if len(applicationids) > 0 {
		for _, v := range applicationids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:applicationIds*/?", strings.Repeat(",?", len(applicationids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:applicationIds*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationCategoriesRow
	for rows.Next() {
		var i GetApplicationCategoriesRow
		if err := rows.Scan(&i.ApplicationID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
