// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_transition_event_document_sources_for_window.sql

package readqueries

import (
	"context"
	"database/sql"
	"time"
)

const listTransitionEventDocumentSourcesForWindow = `-- name: ListTransitionEventDocumentSourcesForWindow :many
SELECT
  timeline.id AS transition_event_id,
  applications.name AS application_name,
  fp0.created_at_utc AS started_at,
  fp1.created_at_utc AS ended_at,
  foreground_process_metadata.browser,
  foreground_process_metadata.tab,
  foreground_process_metadata.idle,
  foreground_process_metadata.cdp_url
FROM timeline
JOIN foreground_processes fp0 ON fp0.id = timeline.initial_foreground_process_id
JOIN foreground_processes fp1 ON fp1.id = timeline.end_foreground_process_id
LEFT JOIN applications ON applications.id = fp0.application_id
LEFT JOIN foreground_process_metadata ON foreground_process_metadata.foreground_process_id = fp0.id
WHERE fp0.created_at_utc < ?1
  AND fp1.created_at_utc > ?2
ORDER BY fp0.created_at_utc ASC, timeline.id ASC
`

type ListTransitionEventDocumentSourcesForWindowParams struct {
	WindowEndedAt   time.Time
	WindowStartedAt time.Time
}

type ListTransitionEventDocumentSourcesForWindowRow struct {
	TransitionEventID int64
	ApplicationName   sql.NullString
	StartedAt         time.Time
	EndedAt           time.Time
	Browser           sql.NullBool
	Tab               *string
	Idle              sql.NullBool
	CdpUrl            *string
}

func (q *Queries) ListTransitionEventDocumentSourcesForWindow(ctx context.Context, arg ListTransitionEventDocumentSourcesForWindowParams) ([]ListTransitionEventDocumentSourcesForWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransitionEventDocumentSourcesForWindow, arg.WindowEndedAt, arg.WindowStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransitionEventDocumentSourcesForWindowRow
	for rows.Next() {
		var i ListTransitionEventDocumentSourcesForWindowRow
		if err := rows.Scan(
			&i.TransitionEventID,
			&i.ApplicationName,
			&i.StartedAt,
			&i.EndedAt,
			&i.Browser,
			&i.Tab,
			&i.Idle,
			&i.CdpUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
