// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_models.sql

package readqueries

import (
	"context"
)

const listModels = `-- name: ListModels :many
SELECT id, semantic, embedding, openrouter_slug, ollama_slug, label
FROM models
ORDER BY id
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Semantic,
			&i.Embedding,
			&i.OpenrouterSlug,
			&i.OllamaSlug,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
