// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_embedding_models.sql

package readqueries

import (
	"context"
)

const listEmbeddingModels = `-- name: ListEmbeddingModels :many
SELECT id, openrouter_slug, ollama_slug, label
FROM embedding_models
ORDER BY id
`

func (q *Queries) ListEmbeddingModels(ctx context.Context) ([]EmbeddingModel, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmbeddingModel
	for rows.Next() {
		var i EmbeddingModel
		if err := rows.Scan(
			&i.ID,
			&i.OpenrouterSlug,
			&i.OllamaSlug,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
