// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_semantic_models.sql

package readqueries

import (
	"context"
)

const listSemanticModels = `-- name: ListSemanticModels :many
SELECT id, openrouter_slug, ollama_slug, label
FROM semantic_models
ORDER BY id
`

func (q *Queries) ListSemanticModels(ctx context.Context) ([]SemanticModel, error) {
	rows, err := q.db.QueryContext(ctx, listSemanticModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SemanticModel
	for rows.Next() {
		var i SemanticModel
		if err := rows.Scan(
			&i.ID,
			&i.OpenrouterSlug,
			&i.OllamaSlug,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
