// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_missing_semantic_event_document_ids.sql

package readqueries

import (
	"context"
	"database/sql"
)

const listMissingSemanticEventDocumentIDs = `-- name: ListMissingSemanticEventDocumentIDs :many
SELECT timeline.id
FROM timeline
LEFT JOIN timeline_semantic_documents
  ON timeline_semantic_documents.timeline_id = timeline.id
  AND timeline_semantic_documents.type = 1
LEFT JOIN timeline_embeddings
  ON timeline_embeddings.timeline_semantic_documents_id = timeline_semantic_documents.id
  AND timeline_embeddings.embedding_model_id = ?
WHERE timeline_semantic_documents.id IS NULL
   OR timeline_embeddings.id IS NULL
ORDER BY timeline.id DESC
LIMIT ?
`

type ListMissingSemanticEventDocumentIDsParams struct {
	EmbeddingModelID sql.NullInt64
	Limit            int64
}

func (q *Queries) ListMissingSemanticEventDocumentIDs(ctx context.Context, arg ListMissingSemanticEventDocumentIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listMissingSemanticEventDocumentIDs, arg.EmbeddingModelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
