// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package readqueries

import (
	"database/sql"
	"time"
)

type EmbeddingModel struct {
	ID             int64
	OpenrouterSlug string
	OllamaSlug     string
	Label          string
}

type Project struct {
	ID              string
	Name            string
	ColorArgb       int64
	Client          string
	HourlyRateCents int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SemanticModel struct {
	ID             int64
	OpenrouterSlug string
	OllamaSlug     string
	Label          string
}

type TimesheetEntry struct {
	ID              string
	TimesheetID     string
	ProjectID       sql.NullString
	Title           string
	Notes           string
	StartMinute     int64
	DurationMinutes int64
	Billable        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
