// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package readqueries

import (
	"database/sql"
)

type Model struct {
	ID             int64
	Semantic       bool
	Embedding      bool
	OpenrouterSlug sql.NullString
	OllamaSlug     sql.NullString
	Label          string
}
