// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package readqueries

type Model struct {
	ID             int64
	Semantic       bool
	Embedding      bool
	OpenrouterSlug *string
	OllamaSlug     *string
	Label          string
}
