// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package readqueries

import (
	"context"
)

const getProjectColorIDByColor = `-- name: GetProjectColorIDByColor :one
SELECT id
FROM project_colors
WHERE color = ?
`

func (q *Queries) GetProjectColorIDByColor(ctx context.Context, color int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProjectColorIDByColor, color)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listProjects = `-- name: ListProjects :many
SELECT
  projects.id,
  projects.name,
  project_colors.color AS color_argb,
  COALESCE(project_details.rate, 0) AS hourly_rate_cents
FROM projects
LEFT JOIN project_details ON project_details.projects_id = projects.id
LEFT JOIN project_colors ON project_colors.id = project_details.project_colors_id
ORDER BY projects.name COLLATE NOCASE, projects.id
`

type ListProjectsRow struct {
	ID              int64
	Name            string
	ColorArgb       *int64
	HourlyRateCents int64
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ColorArgb,
			&i.HourlyRateCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
