// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package readqueries

import (
	"context"
)

type Querier interface {
	GetAISettings(ctx context.Context) (GetAISettingsRow, error)
	GetSemanticEventDocumentSource(ctx context.Context, id int64) (GetSemanticEventDocumentSourceRow, error)
	GetSemanticIndexCounts(ctx context.Context, embeddingModel string) (GetSemanticIndexCountsRow, error)
	GetTransitionEvent(ctx context.Context, id int64) (GetTransitionEventRow, error)
	GetTransitionEvents(ctx context.Context, arg GetTransitionEventsParams) ([]GetTransitionEventsRow, error)
	ListEmbeddingModels(ctx context.Context) ([]EmbeddingModel, error)
	ListMissingSemanticEventDocumentIDs(ctx context.Context, arg ListMissingSemanticEventDocumentIDsParams) ([]int64, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListSemanticModels(ctx context.Context) ([]SemanticModel, error)
	ListTimesheetEntries(ctx context.Context, arg ListTimesheetEntriesParams) ([]TimesheetEntry, error)
	ListTimesheetEntriesInRange(ctx context.Context, arg ListTimesheetEntriesInRangeParams) ([]ListTimesheetEntriesInRangeRow, error)
	ListTimesheetEntryUsageBlocks(ctx context.Context, timesheetEntryID string) ([]string, error)
	ListTransitionEventDocumentSourcesForWindow(ctx context.Context, arg ListTransitionEventDocumentSourcesForWindowParams) ([]ListTransitionEventDocumentSourcesForWindowRow, error)
}

var _ Querier = (*Queries)(nil)
