// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timesheets.sql

package readqueries

import (
	"context"
	"database/sql"
	"time"
)

const listTimesheetEntries = `-- name: ListTimesheetEntries :many
SELECT
  timesheet_entries.id,
  timesheet_entries.timesheet_id,
  timesheet_entries.project_id,
  timesheet_entries.title,
  timesheet_entries.notes,
  timesheet_entries.start_minute,
  timesheet_entries.duration_minutes,
  timesheet_entries.billable,
  timesheet_entries.created_at,
  timesheet_entries.updated_at
FROM timesheet_entries
JOIN timesheets ON timesheets.id = timesheet_entries.timesheet_id
WHERE timesheets.started_at = ? AND timesheets.ended_at = ?
ORDER BY timesheet_entries.start_minute, timesheet_entries.created_at, timesheet_entries.id
`

type ListTimesheetEntriesParams struct {
	StartedAt time.Time
	EndedAt   time.Time
}

func (q *Queries) ListTimesheetEntries(ctx context.Context, arg ListTimesheetEntriesParams) ([]TimesheetEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntries, arg.StartedAt, arg.EndedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimesheetEntry
	for rows.Next() {
		var i TimesheetEntry
		if err := rows.Scan(
			&i.ID,
			&i.TimesheetID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.StartMinute,
			&i.DurationMinutes,
			&i.Billable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimesheetEntriesInRange = `-- name: ListTimesheetEntriesInRange :many
SELECT
  timesheets.started_at,
  timesheets.ended_at,
  timesheet_entries.id,
  timesheet_entries.timesheet_id,
  timesheet_entries.project_id,
  timesheet_entries.title,
  timesheet_entries.notes,
  timesheet_entries.start_minute,
  timesheet_entries.duration_minutes,
  timesheet_entries.billable,
  timesheet_entries.created_at,
  timesheet_entries.updated_at
FROM timesheet_entries
JOIN timesheets ON timesheets.id = timesheet_entries.timesheet_id
WHERE timesheets.started_at >= ? AND timesheets.started_at < ?
ORDER BY timesheets.started_at, timesheet_entries.start_minute, timesheet_entries.created_at, timesheet_entries.id
`

type ListTimesheetEntriesInRangeParams struct {
	StartedAt   time.Time
	StartedAt_2 time.Time
}

type ListTimesheetEntriesInRangeRow struct {
	StartedAt       time.Time
	EndedAt         time.Time
	ID              string
	TimesheetID     string
	ProjectID       sql.NullString
	Title           string
	Notes           string
	StartMinute     int64
	DurationMinutes int64
	Billable        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListTimesheetEntriesInRange(ctx context.Context, arg ListTimesheetEntriesInRangeParams) ([]ListTimesheetEntriesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntriesInRange, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimesheetEntriesInRangeRow
	for rows.Next() {
		var i ListTimesheetEntriesInRangeRow
		if err := rows.Scan(
			&i.StartedAt,
			&i.EndedAt,
			&i.ID,
			&i.TimesheetID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.StartMinute,
			&i.DurationMinutes,
			&i.Billable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimesheetEntryUsageBlocks = `-- name: ListTimesheetEntryUsageBlocks :many
SELECT usage_id
FROM timesheet_entry_usage_blocks
WHERE timesheet_entry_id = ?
ORDER BY sort_order, usage_id
`

func (q *Queries) ListTimesheetEntryUsageBlocks(ctx context.Context, timesheetEntryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntryUsageBlocks, timesheetEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var usage_id string
		if err := rows.Scan(&usage_id); err != nil {
			return nil, err
		}
		items = append(items, usage_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
