// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timesheets.sql

package readqueries

import (
	"context"
	"database/sql"
)

const listTimesheetEntries = `-- name: ListTimesheetEntries :many
SELECT
  ledger_items.id,
  project_costs.projects_id AS project_id,
  ledger_items.title,
  ledger_items.notes,
  ledger_items.billable,
  ledger_items.started_at_utc,
  ledger_items.ended_at_utc
FROM ledger_items
LEFT JOIN project_costs ON project_costs.ledger_items_id = ledger_items.id
WHERE ledger_items.started_at_utc >= ? AND ledger_items.started_at_utc < ?
ORDER BY ledger_items.started_at_utc, ledger_items.id
`

type ListTimesheetEntriesParams struct {
	StartedAtUtc   sql.NullTime
	StartedAtUtc_2 sql.NullTime
}

type ListTimesheetEntriesRow struct {
	ID           int64
	ProjectID    sql.NullInt64
	Title        string
	Notes        sql.NullString
	Billable     bool
	StartedAtUtc sql.NullTime
	EndedAtUtc   sql.NullTime
}

func (q *Queries) ListTimesheetEntries(ctx context.Context, arg ListTimesheetEntriesParams) ([]ListTimesheetEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntries, arg.StartedAtUtc, arg.StartedAtUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimesheetEntriesRow
	for rows.Next() {
		var i ListTimesheetEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Billable,
			&i.StartedAtUtc,
			&i.EndedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimesheetEntriesInRange = `-- name: ListTimesheetEntriesInRange :many
SELECT
  ledger_items.id,
  project_costs.projects_id AS project_id,
  ledger_items.title,
  ledger_items.notes,
  ledger_items.billable,
  ledger_items.started_at_utc,
  ledger_items.ended_at_utc
FROM ledger_items
LEFT JOIN project_costs ON project_costs.ledger_items_id = ledger_items.id
WHERE ledger_items.started_at_utc >= ? AND ledger_items.started_at_utc < ?
ORDER BY ledger_items.started_at_utc, ledger_items.id
`

type ListTimesheetEntriesInRangeParams struct {
	StartedAtUtc   sql.NullTime
	StartedAtUtc_2 sql.NullTime
}

type ListTimesheetEntriesInRangeRow struct {
	ID           int64
	ProjectID    sql.NullInt64
	Title        string
	Notes        sql.NullString
	Billable     bool
	StartedAtUtc sql.NullTime
	EndedAtUtc   sql.NullTime
}

func (q *Queries) ListTimesheetEntriesInRange(ctx context.Context, arg ListTimesheetEntriesInRangeParams) ([]ListTimesheetEntriesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntriesInRange, arg.StartedAtUtc, arg.StartedAtUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimesheetEntriesInRangeRow
	for rows.Next() {
		var i ListTimesheetEntriesInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Notes,
			&i.Billable,
			&i.StartedAtUtc,
			&i.EndedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimesheetEntryUsageBlocks = `-- name: ListTimesheetEntryUsageBlocks :many
SELECT timeline_id
FROM ledger_item_timeline_entries
WHERE ledger_items_id = ?
ORDER BY timeline_id
`

func (q *Queries) ListTimesheetEntryUsageBlocks(ctx context.Context, ledgerItemsID sql.NullInt64) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, listTimesheetEntryUsageBlocks, ledgerItemsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt64
	for rows.Next() {
		var timeline_id sql.NullInt64
		if err := rows.Scan(&timeline_id); err != nil {
			return nil, err
		}
		items = append(items, timeline_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
