//go:build linux

// This file is autogenerated from: ext/ext-idle-notify-v1.xml
// Do not edit

// Package ext implements the ext_idle_notify_v1 protocol
package ext

import (
	"sync"
)

// IdleNotifierV1 idle notification manager
type IdleNotifierV1 struct {
	BaseProxy
}

// NewIdleNotifierV1 is a constructor for the IdleNotifierV1 object
func NewIdleNotifierV1(ctx *Context) *IdleNotifierV1 {
	ret := new(IdleNotifierV1)
	ctx.Register(ret)
	return ret
}

// Destroy destroy the manager
func (p *IdleNotifierV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// GetIdleNotification create a notification object
func (p *IdleNotifierV1) GetIdleNotification(Timeout uint32, Seat *Seat) (*IdleNotificationV1, error) {
	retId := NewIdleNotificationV1(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, Timeout, Seat)
}

// GetInputIdleNotification create a notification object
func (p *IdleNotifierV1) GetInputIdleNotification(Timeout uint32, Seat *Seat) (*IdleNotificationV1, error) {
	retId := NewIdleNotificationV1(p.Context())
	return retId, p.Context().SendRequest(p, 2, retId, Timeout, Seat)
}

// Dispatch dispatches event for object IdleNotifierV1
func (p *IdleNotifierV1) Dispatch(event *Event) {
	switch event.Opcode {

	}
}

// IdleNotificationV1 idle notification
type IdleNotificationV1 struct {
	BaseProxy
	mu                                sync.RWMutex
	privateIdleNotificationV1Idleds   map[IdleNotificationV1IdledHandler]struct{}
	privateIdleNotificationV1Resumeds map[IdleNotificationV1ResumedHandler]struct{}
}

// initIdleNotificationV1 initializes the IdleNotificationV1 object's handler maps
func (ret *IdleNotificationV1) initIdleNotificationV1() {
	ret.privateIdleNotificationV1Idleds = make(map[IdleNotificationV1IdledHandler]struct{})
	ret.privateIdleNotificationV1Resumeds = make(map[IdleNotificationV1ResumedHandler]struct{})
}

// NewIdleNotificationV1 is a constructor for the IdleNotificationV1 object
func NewIdleNotificationV1(ctx *Context) *IdleNotificationV1 {
	ret := new(IdleNotificationV1)
	ret.initIdleNotificationV1()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the notification object
func (p *IdleNotificationV1) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object IdleNotificationV1
func (p *IdleNotificationV1) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateIdleNotificationV1Idleds) > 0 {
			ev := IdleNotificationV1IdledEvent{}
			p.mu.RLock()
			for h := range p.privateIdleNotificationV1Idleds {
				h.HandleIdleNotificationV1Idled(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateIdleNotificationV1Resumeds) > 0 {
			ev := IdleNotificationV1ResumedEvent{}
			p.mu.RLock()
			for h := range p.privateIdleNotificationV1Resumeds {
				h.HandleIdleNotificationV1Resumed(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// IdleNotificationV1IdledEvent is the notification object is idle
type IdleNotificationV1IdledEvent struct {
}

// IdleNotificationV1ResumedEvent is the notification object is no longer idle
type IdleNotificationV1ResumedEvent struct {
}

// IdleNotificationV1IdledHandler is the handler interface for IdleNotificationV1IdledEvent
type IdleNotificationV1IdledHandler interface {
	HandleIdleNotificationV1Idled(IdleNotificationV1IdledEvent)
}

// AddIdledHandler adds the Idled handler
func (p *IdleNotificationV1) AddIdledHandler(h IdleNotificationV1IdledHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateIdleNotificationV1Idleds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveIdledHandler removes the Idled handler
func (p *IdleNotificationV1) RemoveIdledHandler(h IdleNotificationV1IdledHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateIdleNotificationV1Idleds, h)
}

// IdleNotificationV1ResumedHandler is the handler interface for IdleNotificationV1ResumedEvent
type IdleNotificationV1ResumedHandler interface {
	HandleIdleNotificationV1Resumed(IdleNotificationV1ResumedEvent)
}

// AddResumedHandler adds the Resumed handler
func (p *IdleNotificationV1) AddResumedHandler(h IdleNotificationV1ResumedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateIdleNotificationV1Resumeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveResumedHandler removes the Resumed handler
func (p *IdleNotificationV1) RemoveResumedHandler(h IdleNotificationV1ResumedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateIdleNotificationV1Resumeds, h)
}
