// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converters

import (
	models "github.com/skulpturenz/timeboxxing/sidecar/components/application/models"
	models1 "github.com/skulpturenz/timeboxxing/sidecar/components/timeline/models"
)

type ApplicationCategoriesConverter struct{}

func (c *ApplicationCategoriesConverter) MergeAppMetadata(source models.ApplicationCategories, target *models1.AppMetadata) {
	target.Category = firstCategory(source.Categories)
}
