// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converters

import (
	models "github.com/skulpturenz/timeboxxing/sidecar/components/timeline/models"
	readqueries "github.com/skulpturenz/timeboxxing/sidecar/db/read_queries"
	"time"
)

type GetTimelineInitialRowConverter struct{}

func (c *GetTimelineInitialRowConverter) ToForegroundProcess(source readqueries.GetTimelineRow) models.ForegroundProcess {
	var modelsForegroundProcess models.ForegroundProcess
	modelsForegroundProcess.AppName = source.InitialApplicationName
	modelsForegroundProcess.AppIdentifier = source.InitialApplicationIdentifier
	modelsForegroundProcess.AppPath = source.InitialApplicationPath
	modelsForegroundProcess.PID = source.InitialPid
	modelsForegroundProcess.WindowTitle = source.InitialWindowTitle
	modelsForegroundProcess.TitleSource = parseOptionalTitleSource(source.InitialTitleSource)
	modelsForegroundProcess.Timestamp = c.pTimeTimeToTimeTime(source.InitialCreatedAtUtc)
	if source.InitialIdle != nil {
		modelsForegroundProcess.Idle = *source.InitialIdle
	}
	if source.InitialKilled != nil {
		modelsForegroundProcess.Killed = *source.InitialKilled
	}
	modelsForegroundProcess.Enrichments = c.toEnrichments(source)
	return modelsForegroundProcess
}
func (c *GetTimelineInitialRowConverter) pTimeTimeToTimeTime(source *time.Time) time.Time {
	var timeTime time.Time
	if source != nil {
		timeTime = (*source)
	}
	return timeTime
}
func (c *GetTimelineInitialRowConverter) toAppMetadata(source readqueries.GetTimelineRow) models.AppMetadata {
	var modelsAppMetadata models.AppMetadata
	_ = source
	return modelsAppMetadata
}
func (c *GetTimelineInitialRowConverter) toBrowser(source readqueries.GetTimelineRow) models.Browser {
	var modelsBrowser models.Browser
	modelsBrowser.Vendor = initialBrowserVendor(source)
	modelsBrowser.Category = parseOptionalBrowserCategory(source.InitialBrowserCategory)
	if source.InitialTab != nil {
		modelsBrowser.Tab = *source.InitialTab
	}
	if source.InitialCdpUrl != nil {
		modelsBrowser.CdpURL = *source.InitialCdpUrl
	}
	return modelsBrowser
}
func (c *GetTimelineInitialRowConverter) toEnrichments(source readqueries.GetTimelineRow) models.Enrichments {
	var modelsEnrichments models.Enrichments
	modelsEnrichments.Appmetadata = c.toAppMetadata(source)
	modelsEnrichments.Browser = c.toBrowser(source)
	modelsEnrichments.Location = c.toLocation(source)
	return modelsEnrichments
}
func (c *GetTimelineInitialRowConverter) toLocation(source readqueries.GetTimelineRow) models.Location {
	var modelsLocation models.Location
	modelsLocation.Latitude = source.InitialLatitude
	modelsLocation.Longitude = source.InitialLongitude
	modelsLocation.PublicIP = source.InitialPublicIp
	return modelsLocation
}
