// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converters

import (
	models "github.com/skulpturenz/timeboxxing/sidecar/components/timeline/models"
	readqueries "github.com/skulpturenz/timeboxxing/sidecar/db/read_queries"
	"time"
)

type GetTimelineFinalRowConverter struct{}

func (c *GetTimelineFinalRowConverter) ToForegroundProcess(source readqueries.GetTimelineRow) models.ForegroundProcess {
	var modelsForegroundProcess models.ForegroundProcess
	modelsForegroundProcess.AppName = source.FinalApplicationName
	modelsForegroundProcess.AppIdentifier = source.FinalApplicationIdentifier
	modelsForegroundProcess.AppPath = source.FinalApplicationPath
	modelsForegroundProcess.PID = source.FinalPid
	modelsForegroundProcess.WindowTitle = source.FinalWindowTitle
	modelsForegroundProcess.TitleSource = parseOptionalTitleSource(source.FinalTitleSource)
	modelsForegroundProcess.Timestamp = c.pTimeTimeToTimeTime(source.FinalCreatedAtUtc)
	if source.FinalIdle != nil {
		modelsForegroundProcess.Idle = *source.FinalIdle
	}
	if source.FinalKilled != nil {
		modelsForegroundProcess.Killed = *source.FinalKilled
	}
	modelsForegroundProcess.Enrichments = c.toEnrichments(source)
	return modelsForegroundProcess
}
func (c *GetTimelineFinalRowConverter) pTimeTimeToTimeTime(source *time.Time) time.Time {
	var timeTime time.Time
	if source != nil {
		timeTime = (*source)
	}
	return timeTime
}
func (c *GetTimelineFinalRowConverter) toAppMetadata(source readqueries.GetTimelineRow) models.AppMetadata {
	var modelsAppMetadata models.AppMetadata
	_ = source
	return modelsAppMetadata
}
func (c *GetTimelineFinalRowConverter) toBrowser(source readqueries.GetTimelineRow) models.Browser {
	var modelsBrowser models.Browser
	modelsBrowser.Vendor = finalBrowserVendor(source)
	modelsBrowser.Category = parseOptionalBrowserCategory(source.FinalBrowserCategory)
	if source.FinalTab != nil {
		modelsBrowser.Tab = *source.FinalTab
	}
	if source.FinalCdpUrl != nil {
		modelsBrowser.CdpURL = *source.FinalCdpUrl
	}
	return modelsBrowser
}
func (c *GetTimelineFinalRowConverter) toEnrichments(source readqueries.GetTimelineRow) models.Enrichments {
	var modelsEnrichments models.Enrichments
	modelsEnrichments.Appmetadata = c.toAppMetadata(source)
	modelsEnrichments.Browser = c.toBrowser(source)
	modelsEnrichments.Location = c.toLocation(source)
	return modelsEnrichments
}
func (c *GetTimelineFinalRowConverter) toLocation(source readqueries.GetTimelineRow) models.Location {
	var modelsLocation models.Location
	modelsLocation.Latitude = source.FinalLatitude
	modelsLocation.Longitude = source.FinalLongitude
	modelsLocation.PublicIP = source.FinalPublicIp
	return modelsLocation
}
