// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converters

import (
	models "github.com/skulpturenz/timeboxxing/sidecar/components/timeline/models"
	readqueries "github.com/skulpturenz/timeboxxing/sidecar/db/read_queries"
)

type GetUnindexedForegroundProcessesRowConverter struct{}

func (c *GetUnindexedForegroundProcessesRowConverter) ToForegroundProcess(source readqueries.GetUnindexedForegroundProcessesRow) models.ForegroundProcess {
	var modelsForegroundProcess models.ForegroundProcess
	modelsForegroundProcess.AppName = zeroNilString(source.ApplicationName)
	modelsForegroundProcess.AppIdentifier = source.ApplicationIdentifier
	modelsForegroundProcess.PID = source.Pid
	modelsForegroundProcess.WindowTitle = source.WindowTitle
	modelsForegroundProcess.TitleSource = parseTitleSource(source.TitleSource)
	modelsForegroundProcess.Timestamp = source.CreatedAtUtc
	modelsForegroundProcess.Idle = source.Idle
	modelsForegroundProcess.Killed = source.Killed
	modelsForegroundProcess.Enrichments = c.toEnrichments(source)
	return modelsForegroundProcess
}
func (c *GetUnindexedForegroundProcessesRowConverter) toBrowser(source readqueries.GetUnindexedForegroundProcessesRow) models.Browser {
	var modelsBrowser models.Browser
	if source.BrowserVendor != nil {
		modelsBrowser.Vendor = *source.BrowserVendor
	}
	modelsBrowser.Category = parseBrowserCategory(source.BrowserCategory)
	if source.Tab != nil {
		modelsBrowser.Tab = *source.Tab
	}
	return modelsBrowser
}
func (c *GetUnindexedForegroundProcessesRowConverter) toEnrichments(source readqueries.GetUnindexedForegroundProcessesRow) models.Enrichments {
	var modelsEnrichments models.Enrichments
	modelsEnrichments.Browser = c.toBrowser(source)
	modelsEnrichments.Location = c.toLocation(source)
	return modelsEnrichments
}
func (c *GetUnindexedForegroundProcessesRowConverter) toLocation(source readqueries.GetUnindexedForegroundProcessesRow) models.Location {
	var modelsLocation models.Location
	modelsLocation.Latitude = source.Latitude
	modelsLocation.Longitude = source.Longitude
	modelsLocation.PublicIP = source.PublicIp
	return modelsLocation
}
