// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converters

import (
	models "github.com/skulpturenz/timeboxxing/sidecar/components/timeline/models"
	monitor "github.com/skulpturenz/timeboxxing/sidecar/monitor"
)

type MonitorForegroundProcessConverter struct{}

func (c *MonitorForegroundProcessConverter) ToForegroundProcess(source monitor.ForegroundProcess) models.ForegroundProcess {
	var modelsForegroundProcess models.ForegroundProcess
	modelsForegroundProcess.AppName = source.AppName
	modelsForegroundProcess.AppIdentifier = source.AppIdentifier
	modelsForegroundProcess.AppPath = source.AppPath
	modelsForegroundProcess.PID = pidInt32ToInt64(source.PID)
	modelsForegroundProcess.WindowTitle = source.WindowTitle
	modelsForegroundProcess.Timestamp = source.Timestamp
	modelsForegroundProcess.Idle = source.Idle
	modelsForegroundProcess.Enrichments = monitorEnrichments(source)
	return modelsForegroundProcess
}
