//go:build linux

// This file is autogenerated from: plasma/plasma-window-management.xml
// Do not edit

// Package plasma implements the plasma_window_management protocol
package plasma

import (
	"sync"
)

// OrgKdeWindowManagementStateActive
const OrgKdeWindowManagementStateActive = 0x1

// OrgKdeWindowManagementStateMinimized
const OrgKdeWindowManagementStateMinimized = 0x2

// OrgKdeWindowManagementStateMaximized
const OrgKdeWindowManagementStateMaximized = 0x4

// OrgKdeWindowManagementStateFullscreen
const OrgKdeWindowManagementStateFullscreen = 0x8

// OrgKdeWindowManagementStateKeepAbove
const OrgKdeWindowManagementStateKeepAbove = 0x10

// OrgKdeWindowManagementStateKeepBelow
const OrgKdeWindowManagementStateKeepBelow = 0x20

// OrgKdeWindowManagementStateOnAllDesktops
const OrgKdeWindowManagementStateOnAllDesktops = 0x40

// OrgKdeWindowManagementStateDemandsAttention
const OrgKdeWindowManagementStateDemandsAttention = 0x80

// OrgKdeWindowManagementStateCloseable
const OrgKdeWindowManagementStateCloseable = 0x100

// OrgKdeWindowManagementStateMinimizable
const OrgKdeWindowManagementStateMinimizable = 0x200

// OrgKdeWindowManagementStateMaximizable
const OrgKdeWindowManagementStateMaximizable = 0x400

// OrgKdeWindowManagementStateFullscreenable
const OrgKdeWindowManagementStateFullscreenable = 0x800

// OrgKdeWindowManagementStateSkiptaskbar
const OrgKdeWindowManagementStateSkiptaskbar = 0x1000

// OrgKdeWindowManagementStateShadeable
const OrgKdeWindowManagementStateShadeable = 0x2000

// OrgKdeWindowManagementStateShaded
const OrgKdeWindowManagementStateShaded = 0x4000

// OrgKdeWindowManagementStateMovable
const OrgKdeWindowManagementStateMovable = 0x8000

// OrgKdeWindowManagementStateResizable
const OrgKdeWindowManagementStateResizable = 0x10000

// OrgKdeWindowManagementStateVirtualDesktopChangeable
const OrgKdeWindowManagementStateVirtualDesktopChangeable = 0x20000

// OrgKdeWindowManagementStateSkipswitcher
const OrgKdeWindowManagementStateSkipswitcher = 0x40000

// OrgKdeWindowManagementStateNoBorder
const OrgKdeWindowManagementStateNoBorder = 0x80000

// OrgKdeWindowManagementStateCanSetNoBorder
const OrgKdeWindowManagementStateCanSetNoBorder = 0x100000

// OrgKdeWindowManagementStateExcludeFromCapture
const OrgKdeWindowManagementStateExcludeFromCapture = 0x200000

// OrgKdeWindowManagementShowDesktopDisabled
const OrgKdeWindowManagementShowDesktopDisabled = 0

// OrgKdeWindowManagementShowDesktopEnabled
const OrgKdeWindowManagementShowDesktopEnabled = 1

// OrgKdeWindowManagement application windows management
type OrgKdeWindowManagement struct {
	BaseProxy
	mu                                                     sync.RWMutex
	privateOrgKdeWindowManagementShowDesktopChangeds       map[OrgKdeWindowManagementShowDesktopChangedHandler]struct{}
	privateOrgKdeWindowManagementWindows                   map[OrgKdeWindowManagementWindowHandler]struct{}
	privateOrgKdeWindowManagementStackingOrderChangeds     map[OrgKdeWindowManagementStackingOrderChangedHandler]struct{}
	privateOrgKdeWindowManagementStackingOrderUuidChangeds map[OrgKdeWindowManagementStackingOrderUuidChangedHandler]struct{}
	privateOrgKdeWindowManagementWindowWithUuids           map[OrgKdeWindowManagementWindowWithUuidHandler]struct{}
	privateOrgKdeWindowManagementStackingOrderChanged2s    map[OrgKdeWindowManagementStackingOrderChanged2Handler]struct{}
}

// initOrgKdeWindowManagement initializes the OrgKdeWindowManagement object's handler maps
func (ret *OrgKdeWindowManagement) initOrgKdeWindowManagement() {
	ret.privateOrgKdeWindowManagementShowDesktopChangeds = make(map[OrgKdeWindowManagementShowDesktopChangedHandler]struct{})
	ret.privateOrgKdeWindowManagementWindows = make(map[OrgKdeWindowManagementWindowHandler]struct{})
	ret.privateOrgKdeWindowManagementStackingOrderChangeds = make(map[OrgKdeWindowManagementStackingOrderChangedHandler]struct{})
	ret.privateOrgKdeWindowManagementStackingOrderUuidChangeds = make(map[OrgKdeWindowManagementStackingOrderUuidChangedHandler]struct{})
	ret.privateOrgKdeWindowManagementWindowWithUuids = make(map[OrgKdeWindowManagementWindowWithUuidHandler]struct{})
	ret.privateOrgKdeWindowManagementStackingOrderChanged2s = make(map[OrgKdeWindowManagementStackingOrderChanged2Handler]struct{})
}

// NewOrgKdeWindowManagement is a constructor for the OrgKdeWindowManagement object
func NewOrgKdeWindowManagement(ctx *Context) *OrgKdeWindowManagement {
	ret := new(OrgKdeWindowManagement)
	ret.initOrgKdeWindowManagement()
	ctx.Register(ret)
	return ret
}

// ShowDesktop show/hide the desktop
func (p *OrgKdeWindowManagement) ShowDesktop(State uint32) error {

	return p.Context().SendRequest(p, 0, State)
}

// GetWindow deprecated
func (p *OrgKdeWindowManagement) GetWindow(InternalWindowId uint32) (*OrgKdeWindow, error) {
	retId := NewOrgKdeWindow(p.Context())
	return retId, p.Context().SendRequest(p, 1, retId, InternalWindowId)
}

// GetWindowByUuid
func (p *OrgKdeWindowManagement) GetWindowByUuid(InternalWindowUuid string) (*OrgKdeWindow, error) {
	retId := NewOrgKdeWindow(p.Context())
	return retId, p.Context().SendRequest(p, 2, retId, InternalWindowUuid)
}

// GetStackingOrder get the stacking order
func (p *OrgKdeWindowManagement) GetStackingOrder() (*OrgKdeStackingOrder, error) {
	retStackingOrder := NewOrgKdeStackingOrder(p.Context())
	return retStackingOrder, p.Context().SendRequest(p, 3, retStackingOrder)
}

// Dispatch dispatches event for object OrgKdeWindowManagement
func (p *OrgKdeWindowManagement) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateOrgKdeWindowManagementShowDesktopChangeds) > 0 {
			ev := OrgKdeWindowManagementShowDesktopChangedEvent{}
			ev.State = event.Uint32()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowManagementShowDesktopChangeds {
				h.HandleOrgKdeWindowManagementShowDesktopChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateOrgKdeWindowManagementWindows) > 0 {
			ev := OrgKdeWindowManagementWindowEvent{}
			ev.Id = event.Uint32()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowManagementWindows {
				h.HandleOrgKdeWindowManagementWindow(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateOrgKdeWindowManagementStackingOrderChangeds) > 0 {
			ev := OrgKdeWindowManagementStackingOrderChangedEvent{}
			ev.Ids = event.Array()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowManagementStackingOrderChangeds {
				h.HandleOrgKdeWindowManagementStackingOrderChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateOrgKdeWindowManagementStackingOrderUuidChangeds) > 0 {
			ev := OrgKdeWindowManagementStackingOrderUuidChangedEvent{}
			ev.Uuids = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowManagementStackingOrderUuidChangeds {
				h.HandleOrgKdeWindowManagementStackingOrderUuidChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateOrgKdeWindowManagementWindowWithUuids) > 0 {
			ev := OrgKdeWindowManagementWindowWithUuidEvent{}
			ev.Id = event.Uint32()
			ev.Uuid = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowManagementWindowWithUuids {
				h.HandleOrgKdeWindowManagementWindowWithUuid(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateOrgKdeWindowManagementStackingOrderChanged2s) > 0 {
			ev := OrgKdeWindowManagementStackingOrderChanged2Event{}
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowManagementStackingOrderChanged2s {
				h.HandleOrgKdeWindowManagementStackingOrderChanged2(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// OrgKdeWindowManagementShowDesktopChangedEvent is the notify the client when the show desktop mode is entered/left
type OrgKdeWindowManagementShowDesktopChangedEvent struct {
	// State is the new state
	State uint32
}

// OrgKdeWindowManagementWindowEvent is the notify the client that a window was mapped
type OrgKdeWindowManagementWindowEvent struct {
	// Id is the Deprecated: internal window Id
	Id uint32
}

// OrgKdeWindowManagementStackingOrderChangedEvent is the notify the client when stacking order changed
type OrgKdeWindowManagementStackingOrderChangedEvent struct {
	// Ids is the internal windows id array
	Ids []int32
}

// OrgKdeWindowManagementStackingOrderUuidChangedEvent is the notify the client when stacking order changed
type OrgKdeWindowManagementStackingOrderUuidChangedEvent struct {
	// Uuids is the internal windows id ;-separated
	Uuids string
}

// OrgKdeWindowManagementWindowWithUuidEvent is the notify the client that a window was mapped
type OrgKdeWindowManagementWindowWithUuidEvent struct {
	// Id is the Deprecated: internal window Id
	Id uint32
	// Uuid is the internal window uuid
	Uuid string
}

// OrgKdeWindowManagementStackingOrderChanged2Event is the notify the client when stacking order changed
type OrgKdeWindowManagementStackingOrderChanged2Event struct {
}

// OrgKdeWindowManagementShowDesktopChangedHandler is the handler interface for OrgKdeWindowManagementShowDesktopChangedEvent
type OrgKdeWindowManagementShowDesktopChangedHandler interface {
	HandleOrgKdeWindowManagementShowDesktopChanged(OrgKdeWindowManagementShowDesktopChangedEvent)
}

// AddShowDesktopChangedHandler adds the ShowDesktopChanged handler
func (p *OrgKdeWindowManagement) AddShowDesktopChangedHandler(h OrgKdeWindowManagementShowDesktopChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowManagementShowDesktopChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveShowDesktopChangedHandler removes the ShowDesktopChanged handler
func (p *OrgKdeWindowManagement) RemoveShowDesktopChangedHandler(h OrgKdeWindowManagementShowDesktopChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowManagementShowDesktopChangeds, h)
}

// OrgKdeWindowManagementWindowHandler is the handler interface for OrgKdeWindowManagementWindowEvent
type OrgKdeWindowManagementWindowHandler interface {
	HandleOrgKdeWindowManagementWindow(OrgKdeWindowManagementWindowEvent)
}

// AddWindowHandler adds the Window handler
func (p *OrgKdeWindowManagement) AddWindowHandler(h OrgKdeWindowManagementWindowHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowManagementWindows[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveWindowHandler removes the Window handler
func (p *OrgKdeWindowManagement) RemoveWindowHandler(h OrgKdeWindowManagementWindowHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowManagementWindows, h)
}

// OrgKdeWindowManagementStackingOrderChangedHandler is the handler interface for OrgKdeWindowManagementStackingOrderChangedEvent
type OrgKdeWindowManagementStackingOrderChangedHandler interface {
	HandleOrgKdeWindowManagementStackingOrderChanged(OrgKdeWindowManagementStackingOrderChangedEvent)
}

// AddStackingOrderChangedHandler adds the StackingOrderChanged handler
func (p *OrgKdeWindowManagement) AddStackingOrderChangedHandler(h OrgKdeWindowManagementStackingOrderChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowManagementStackingOrderChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStackingOrderChangedHandler removes the StackingOrderChanged handler
func (p *OrgKdeWindowManagement) RemoveStackingOrderChangedHandler(h OrgKdeWindowManagementStackingOrderChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowManagementStackingOrderChangeds, h)
}

// OrgKdeWindowManagementStackingOrderUuidChangedHandler is the handler interface for OrgKdeWindowManagementStackingOrderUuidChangedEvent
type OrgKdeWindowManagementStackingOrderUuidChangedHandler interface {
	HandleOrgKdeWindowManagementStackingOrderUuidChanged(OrgKdeWindowManagementStackingOrderUuidChangedEvent)
}

// AddStackingOrderUuidChangedHandler adds the StackingOrderUuidChanged handler
func (p *OrgKdeWindowManagement) AddStackingOrderUuidChangedHandler(h OrgKdeWindowManagementStackingOrderUuidChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowManagementStackingOrderUuidChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStackingOrderUuidChangedHandler removes the StackingOrderUuidChanged handler
func (p *OrgKdeWindowManagement) RemoveStackingOrderUuidChangedHandler(h OrgKdeWindowManagementStackingOrderUuidChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowManagementStackingOrderUuidChangeds, h)
}

// OrgKdeWindowManagementWindowWithUuidHandler is the handler interface for OrgKdeWindowManagementWindowWithUuidEvent
type OrgKdeWindowManagementWindowWithUuidHandler interface {
	HandleOrgKdeWindowManagementWindowWithUuid(OrgKdeWindowManagementWindowWithUuidEvent)
}

// AddWindowWithUuidHandler adds the WindowWithUuid handler
func (p *OrgKdeWindowManagement) AddWindowWithUuidHandler(h OrgKdeWindowManagementWindowWithUuidHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowManagementWindowWithUuids[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveWindowWithUuidHandler removes the WindowWithUuid handler
func (p *OrgKdeWindowManagement) RemoveWindowWithUuidHandler(h OrgKdeWindowManagementWindowWithUuidHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowManagementWindowWithUuids, h)
}

// OrgKdeWindowManagementStackingOrderChanged2Handler is the handler interface for OrgKdeWindowManagementStackingOrderChanged2Event
type OrgKdeWindowManagementStackingOrderChanged2Handler interface {
	HandleOrgKdeWindowManagementStackingOrderChanged2(OrgKdeWindowManagementStackingOrderChanged2Event)
}

// AddStackingOrderChanged2Handler adds the StackingOrderChanged2 handler
func (p *OrgKdeWindowManagement) AddStackingOrderChanged2Handler(h OrgKdeWindowManagementStackingOrderChanged2Handler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowManagementStackingOrderChanged2s[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStackingOrderChanged2Handler removes the StackingOrderChanged2 handler
func (p *OrgKdeWindowManagement) RemoveStackingOrderChanged2Handler(h OrgKdeWindowManagementStackingOrderChanged2Handler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowManagementStackingOrderChanged2s, h)
}

// OrgKdeWindow interface to control application windows
type OrgKdeWindow struct {
	BaseProxy
	mu                                        sync.RWMutex
	privateOrgKdeWindowTitleChangeds          map[OrgKdeWindowTitleChangedHandler]struct{}
	privateOrgKdeWindowAppIdChangeds          map[OrgKdeWindowAppIdChangedHandler]struct{}
	privateOrgKdeWindowStateChangeds          map[OrgKdeWindowStateChangedHandler]struct{}
	privateOrgKdeWindowVirtualDesktopChangeds map[OrgKdeWindowVirtualDesktopChangedHandler]struct{}
	privateOrgKdeWindowThemedIconNameChangeds map[OrgKdeWindowThemedIconNameChangedHandler]struct{}
	privateOrgKdeWindowUnmappeds              map[OrgKdeWindowUnmappedHandler]struct{}
	privateOrgKdeWindowInitialStates          map[OrgKdeWindowInitialStateHandler]struct{}
	privateOrgKdeWindowParentWindows          map[OrgKdeWindowParentWindowHandler]struct{}
	privateOrgKdeWindowGeometrys              map[OrgKdeWindowGeometryHandler]struct{}
	privateOrgKdeWindowIconChangeds           map[OrgKdeWindowIconChangedHandler]struct{}
	privateOrgKdeWindowPidChangeds            map[OrgKdeWindowPidChangedHandler]struct{}
	privateOrgKdeWindowVirtualDesktopEntereds map[OrgKdeWindowVirtualDesktopEnteredHandler]struct{}
	privateOrgKdeWindowVirtualDesktopLefts    map[OrgKdeWindowVirtualDesktopLeftHandler]struct{}
	privateOrgKdeWindowApplicationMenus       map[OrgKdeWindowApplicationMenuHandler]struct{}
	privateOrgKdeWindowActivityEntereds       map[OrgKdeWindowActivityEnteredHandler]struct{}
	privateOrgKdeWindowActivityLefts          map[OrgKdeWindowActivityLeftHandler]struct{}
	privateOrgKdeWindowResourceNameChangeds   map[OrgKdeWindowResourceNameChangedHandler]struct{}
	privateOrgKdeWindowClientGeometrys        map[OrgKdeWindowClientGeometryHandler]struct{}
}

// initOrgKdeWindow initializes the OrgKdeWindow object's handler maps
func (ret *OrgKdeWindow) initOrgKdeWindow() {
	ret.privateOrgKdeWindowTitleChangeds = make(map[OrgKdeWindowTitleChangedHandler]struct{})
	ret.privateOrgKdeWindowAppIdChangeds = make(map[OrgKdeWindowAppIdChangedHandler]struct{})
	ret.privateOrgKdeWindowStateChangeds = make(map[OrgKdeWindowStateChangedHandler]struct{})
	ret.privateOrgKdeWindowVirtualDesktopChangeds = make(map[OrgKdeWindowVirtualDesktopChangedHandler]struct{})
	ret.privateOrgKdeWindowThemedIconNameChangeds = make(map[OrgKdeWindowThemedIconNameChangedHandler]struct{})
	ret.privateOrgKdeWindowUnmappeds = make(map[OrgKdeWindowUnmappedHandler]struct{})
	ret.privateOrgKdeWindowInitialStates = make(map[OrgKdeWindowInitialStateHandler]struct{})
	ret.privateOrgKdeWindowParentWindows = make(map[OrgKdeWindowParentWindowHandler]struct{})
	ret.privateOrgKdeWindowGeometrys = make(map[OrgKdeWindowGeometryHandler]struct{})
	ret.privateOrgKdeWindowIconChangeds = make(map[OrgKdeWindowIconChangedHandler]struct{})
	ret.privateOrgKdeWindowPidChangeds = make(map[OrgKdeWindowPidChangedHandler]struct{})
	ret.privateOrgKdeWindowVirtualDesktopEntereds = make(map[OrgKdeWindowVirtualDesktopEnteredHandler]struct{})
	ret.privateOrgKdeWindowVirtualDesktopLefts = make(map[OrgKdeWindowVirtualDesktopLeftHandler]struct{})
	ret.privateOrgKdeWindowApplicationMenus = make(map[OrgKdeWindowApplicationMenuHandler]struct{})
	ret.privateOrgKdeWindowActivityEntereds = make(map[OrgKdeWindowActivityEnteredHandler]struct{})
	ret.privateOrgKdeWindowActivityLefts = make(map[OrgKdeWindowActivityLeftHandler]struct{})
	ret.privateOrgKdeWindowResourceNameChangeds = make(map[OrgKdeWindowResourceNameChangedHandler]struct{})
	ret.privateOrgKdeWindowClientGeometrys = make(map[OrgKdeWindowClientGeometryHandler]struct{})
}

// NewOrgKdeWindow is a constructor for the OrgKdeWindow object
func NewOrgKdeWindow(ctx *Context) *OrgKdeWindow {
	ret := new(OrgKdeWindow)
	ret.initOrgKdeWindow()
	ctx.Register(ret)
	return ret
}

// SetState set window state
func (p *OrgKdeWindow) SetState(Flags uint32, State uint32) error {

	return p.Context().SendRequest(p, 0, Flags, State)
}

// SetVirtualDesktop map window on a virtual desktop
func (p *OrgKdeWindow) SetVirtualDesktop(Number uint32) error {

	return p.Context().SendRequest(p, 1, Number)
}

// SetMinimizedGeometry set the geometry for a taskbar entry
func (p *OrgKdeWindow) SetMinimizedGeometry(Panel *Surface, X uint32, Y uint32, Width uint32, Height uint32) error {

	return p.Context().SendRequest(p, 2, Panel, X, Y, Width, Height)
}

// UnsetMinimizedGeometry set the geometry for a taskbar entry
func (p *OrgKdeWindow) UnsetMinimizedGeometry(Panel *Surface) error {

	return p.Context().SendRequest(p, 3, Panel)
}

// Close close window
func (p *OrgKdeWindow) Close() error {

	return p.Context().SendRequest(p, 4)
}

// RequestMove request move
func (p *OrgKdeWindow) RequestMove() error {

	return p.Context().SendRequest(p, 5)
}

// RequestResize request resize
func (p *OrgKdeWindow) RequestResize() error {

	return p.Context().SendRequest(p, 6)
}

// Destroy remove resource for the org_kde_plasma_window
func (p *OrgKdeWindow) Destroy() error {

	return p.Context().SendRequest(p, 7)
}

// GetIcon Requests to get the window icon
func (p *OrgKdeWindow) GetIcon(Fd uintptr) error {

	return p.Context().SendRequest(p, 8, Fd)
}

// RequestEnterVirtualDesktop map window on a virtual desktop
func (p *OrgKdeWindow) RequestEnterVirtualDesktop(Id string) error {

	return p.Context().SendRequest(p, 9, Id)
}

// RequestEnterNewVirtualDesktop map window on a virtual desktop
func (p *OrgKdeWindow) RequestEnterNewVirtualDesktop() error {

	return p.Context().SendRequest(p, 10)
}

// RequestLeaveVirtualDesktop remove a window from a virtual desktop
func (p *OrgKdeWindow) RequestLeaveVirtualDesktop(Id string) error {

	return p.Context().SendRequest(p, 11, Id)
}

// RequestEnterActivity map window on an activity
func (p *OrgKdeWindow) RequestEnterActivity(Id string) error {

	return p.Context().SendRequest(p, 12, Id)
}

// RequestLeaveActivity remove a window from an activity
func (p *OrgKdeWindow) RequestLeaveActivity(Id string) error {

	return p.Context().SendRequest(p, 13, Id)
}

// SendToOutput send window to specified output
func (p *OrgKdeWindow) SendToOutput(Output *Output) error {

	return p.Context().SendRequest(p, 14, Output)
}

// Dispatch dispatches event for object OrgKdeWindow
func (p *OrgKdeWindow) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateOrgKdeWindowTitleChangeds) > 0 {
			ev := OrgKdeWindowTitleChangedEvent{}
			ev.Title = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowTitleChangeds {
				h.HandleOrgKdeWindowTitleChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateOrgKdeWindowAppIdChangeds) > 0 {
			ev := OrgKdeWindowAppIdChangedEvent{}
			ev.AppId = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowAppIdChangeds {
				h.HandleOrgKdeWindowAppIdChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 2:
		if len(p.privateOrgKdeWindowStateChangeds) > 0 {
			ev := OrgKdeWindowStateChangedEvent{}
			ev.Flags = event.Uint32()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowStateChangeds {
				h.HandleOrgKdeWindowStateChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 3:
		if len(p.privateOrgKdeWindowVirtualDesktopChangeds) > 0 {
			ev := OrgKdeWindowVirtualDesktopChangedEvent{}
			ev.Number = event.Int32()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowVirtualDesktopChangeds {
				h.HandleOrgKdeWindowVirtualDesktopChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 4:
		if len(p.privateOrgKdeWindowThemedIconNameChangeds) > 0 {
			ev := OrgKdeWindowThemedIconNameChangedEvent{}
			ev.Name = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowThemedIconNameChangeds {
				h.HandleOrgKdeWindowThemedIconNameChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 5:
		if len(p.privateOrgKdeWindowUnmappeds) > 0 {
			ev := OrgKdeWindowUnmappedEvent{}
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowUnmappeds {
				h.HandleOrgKdeWindowUnmapped(ev)
			}
			p.mu.RUnlock()
		}
	case 6:
		if len(p.privateOrgKdeWindowInitialStates) > 0 {
			ev := OrgKdeWindowInitialStateEvent{}
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowInitialStates {
				h.HandleOrgKdeWindowInitialState(ev)
			}
			p.mu.RUnlock()
		}
	case 7:
		if len(p.privateOrgKdeWindowParentWindows) > 0 {
			ev := OrgKdeWindowParentWindowEvent{}
			ev.Parent = SafeCast[*OrgKdeWindow](event.Proxy(p.Context()))
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowParentWindows {
				h.HandleOrgKdeWindowParentWindow(ev)
			}
			p.mu.RUnlock()
		}
	case 8:
		if len(p.privateOrgKdeWindowGeometrys) > 0 {
			ev := OrgKdeWindowGeometryEvent{}
			ev.X = event.Int32()
			ev.Y = event.Int32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowGeometrys {
				h.HandleOrgKdeWindowGeometry(ev)
			}
			p.mu.RUnlock()
		}
	case 9:
		if len(p.privateOrgKdeWindowIconChangeds) > 0 {
			ev := OrgKdeWindowIconChangedEvent{}
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowIconChangeds {
				h.HandleOrgKdeWindowIconChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 10:
		if len(p.privateOrgKdeWindowPidChangeds) > 0 {
			ev := OrgKdeWindowPidChangedEvent{}
			ev.Pid = event.Uint32()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowPidChangeds {
				h.HandleOrgKdeWindowPidChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 11:
		if len(p.privateOrgKdeWindowVirtualDesktopEntereds) > 0 {
			ev := OrgKdeWindowVirtualDesktopEnteredEvent{}
			ev.Id = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowVirtualDesktopEntereds {
				h.HandleOrgKdeWindowVirtualDesktopEntered(ev)
			}
			p.mu.RUnlock()
		}
	case 12:
		if len(p.privateOrgKdeWindowVirtualDesktopLefts) > 0 {
			ev := OrgKdeWindowVirtualDesktopLeftEvent{}
			ev.Is = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowVirtualDesktopLefts {
				h.HandleOrgKdeWindowVirtualDesktopLeft(ev)
			}
			p.mu.RUnlock()
		}
	case 13:
		if len(p.privateOrgKdeWindowApplicationMenus) > 0 {
			ev := OrgKdeWindowApplicationMenuEvent{}
			ev.ServiceName = event.String()
			ev.ObjectPath = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowApplicationMenus {
				h.HandleOrgKdeWindowApplicationMenu(ev)
			}
			p.mu.RUnlock()
		}
	case 14:
		if len(p.privateOrgKdeWindowActivityEntereds) > 0 {
			ev := OrgKdeWindowActivityEnteredEvent{}
			ev.Id = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowActivityEntereds {
				h.HandleOrgKdeWindowActivityEntered(ev)
			}
			p.mu.RUnlock()
		}
	case 15:
		if len(p.privateOrgKdeWindowActivityLefts) > 0 {
			ev := OrgKdeWindowActivityLeftEvent{}
			ev.Id = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowActivityLefts {
				h.HandleOrgKdeWindowActivityLeft(ev)
			}
			p.mu.RUnlock()
		}
	case 16:
		if len(p.privateOrgKdeWindowResourceNameChangeds) > 0 {
			ev := OrgKdeWindowResourceNameChangedEvent{}
			ev.ResourceName = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowResourceNameChangeds {
				h.HandleOrgKdeWindowResourceNameChanged(ev)
			}
			p.mu.RUnlock()
		}
	case 17:
		if len(p.privateOrgKdeWindowClientGeometrys) > 0 {
			ev := OrgKdeWindowClientGeometryEvent{}
			ev.X = event.Int32()
			ev.Y = event.Int32()
			ev.Width = event.Uint32()
			ev.Height = event.Uint32()
			p.mu.RLock()
			for h := range p.privateOrgKdeWindowClientGeometrys {
				h.HandleOrgKdeWindowClientGeometry(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// OrgKdeWindowTitleChangedEvent is the window title has been changed
type OrgKdeWindowTitleChangedEvent struct {
	// Title is the window title
	Title string
}

// OrgKdeWindowAppIdChangedEvent is the application identifier has been changed
type OrgKdeWindowAppIdChangedEvent struct {
	// AppId is the
	AppId string
}

// OrgKdeWindowStateChangedEvent is the window state has been changed
type OrgKdeWindowStateChangedEvent struct {
	// Flags is the bitfield of state flags
	Flags uint32
}

// OrgKdeWindowVirtualDesktopChangedEvent is the window was moved to another workspace
type OrgKdeWindowVirtualDesktopChangedEvent struct {
	// Number is the zero based virtual desktop number
	Number int32
}

// OrgKdeWindowThemedIconNameChangedEvent is the window's icon name changed
type OrgKdeWindowThemedIconNameChangedEvent struct {
	// Name is the the new themed icon name
	Name string
}

// OrgKdeWindowUnmappedEvent is the window's surface was unmapped
type OrgKdeWindowUnmappedEvent struct {
}

// OrgKdeWindowInitialStateEvent is the All initial known state is submitted
type OrgKdeWindowInitialStateEvent struct {
}

// OrgKdeWindowParentWindowEvent is the The parent window changed
type OrgKdeWindowParentWindowEvent struct {
	// Parent is the The parent window
	Parent *OrgKdeWindow
}

// OrgKdeWindowGeometryEvent is the The geometry of this window in absolute coordinates
type OrgKdeWindowGeometryEvent struct {
	// X is the x position of the org_kde_plasma_window
	X int32
	// Y is the y position of the org_kde_plasma_window
	Y int32
	// Width is the width of the org_kde_plasma_window
	Width uint32
	// Height is the height of the org_kde_plasma_window
	Height uint32
}

// OrgKdeWindowIconChangedEvent is the The icon of the window changed
type OrgKdeWindowIconChangedEvent struct {
}

// OrgKdeWindowPidChangedEvent is the process id of application owning the window has changed
type OrgKdeWindowPidChangedEvent struct {
	// Pid is the process id
	Pid uint32
}

// OrgKdeWindowVirtualDesktopEnteredEvent is the the window entered a new virtual desktop
type OrgKdeWindowVirtualDesktopEnteredEvent struct {
	// Id is the desktop id
	Id string
}

// OrgKdeWindowVirtualDesktopLeftEvent is the the window left a virtual desktop
type OrgKdeWindowVirtualDesktopLeftEvent struct {
	// Is is the desktop id
	Is string
}

// OrgKdeWindowApplicationMenuEvent is the notify the client that the current appmenu changed
type OrgKdeWindowApplicationMenuEvent struct {
	// ServiceName is the
	ServiceName string
	// ObjectPath is the
	ObjectPath string
}

// OrgKdeWindowActivityEnteredEvent is the the window entered an activity
type OrgKdeWindowActivityEnteredEvent struct {
	// Id is the activity id
	Id string
}

// OrgKdeWindowActivityLeftEvent is the the window left an activity
type OrgKdeWindowActivityLeftEvent struct {
	// Id is the activity id
	Id string
}

// OrgKdeWindowResourceNameChangedEvent is the X11 resource name has changed
type OrgKdeWindowResourceNameChangedEvent struct {
	// ResourceName is the resource name
	ResourceName string
}

// OrgKdeWindowClientGeometryEvent is the The client geometry (i.e. without decorations etc) of this window in absolute coordinates
type OrgKdeWindowClientGeometryEvent struct {
	// X is the x position of the org_kde_plasma_window
	X int32
	// Y is the y position of the org_kde_plasma_window
	Y int32
	// Width is the width of the org_kde_plasma_window
	Width uint32
	// Height is the height of the org_kde_plasma_window
	Height uint32
}

// OrgKdeWindowTitleChangedHandler is the handler interface for OrgKdeWindowTitleChangedEvent
type OrgKdeWindowTitleChangedHandler interface {
	HandleOrgKdeWindowTitleChanged(OrgKdeWindowTitleChangedEvent)
}

// AddTitleChangedHandler adds the TitleChanged handler
func (p *OrgKdeWindow) AddTitleChangedHandler(h OrgKdeWindowTitleChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowTitleChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveTitleChangedHandler removes the TitleChanged handler
func (p *OrgKdeWindow) RemoveTitleChangedHandler(h OrgKdeWindowTitleChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowTitleChangeds, h)
}

// OrgKdeWindowAppIdChangedHandler is the handler interface for OrgKdeWindowAppIdChangedEvent
type OrgKdeWindowAppIdChangedHandler interface {
	HandleOrgKdeWindowAppIdChanged(OrgKdeWindowAppIdChangedEvent)
}

// AddAppIdChangedHandler adds the AppIdChanged handler
func (p *OrgKdeWindow) AddAppIdChangedHandler(h OrgKdeWindowAppIdChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowAppIdChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveAppIdChangedHandler removes the AppIdChanged handler
func (p *OrgKdeWindow) RemoveAppIdChangedHandler(h OrgKdeWindowAppIdChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowAppIdChangeds, h)
}

// OrgKdeWindowStateChangedHandler is the handler interface for OrgKdeWindowStateChangedEvent
type OrgKdeWindowStateChangedHandler interface {
	HandleOrgKdeWindowStateChanged(OrgKdeWindowStateChangedEvent)
}

// AddStateChangedHandler adds the StateChanged handler
func (p *OrgKdeWindow) AddStateChangedHandler(h OrgKdeWindowStateChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowStateChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveStateChangedHandler removes the StateChanged handler
func (p *OrgKdeWindow) RemoveStateChangedHandler(h OrgKdeWindowStateChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowStateChangeds, h)
}

// OrgKdeWindowVirtualDesktopChangedHandler is the handler interface for OrgKdeWindowVirtualDesktopChangedEvent
type OrgKdeWindowVirtualDesktopChangedHandler interface {
	HandleOrgKdeWindowVirtualDesktopChanged(OrgKdeWindowVirtualDesktopChangedEvent)
}

// AddVirtualDesktopChangedHandler adds the VirtualDesktopChanged handler
func (p *OrgKdeWindow) AddVirtualDesktopChangedHandler(h OrgKdeWindowVirtualDesktopChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowVirtualDesktopChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveVirtualDesktopChangedHandler removes the VirtualDesktopChanged handler
func (p *OrgKdeWindow) RemoveVirtualDesktopChangedHandler(h OrgKdeWindowVirtualDesktopChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowVirtualDesktopChangeds, h)
}

// OrgKdeWindowThemedIconNameChangedHandler is the handler interface for OrgKdeWindowThemedIconNameChangedEvent
type OrgKdeWindowThemedIconNameChangedHandler interface {
	HandleOrgKdeWindowThemedIconNameChanged(OrgKdeWindowThemedIconNameChangedEvent)
}

// AddThemedIconNameChangedHandler adds the ThemedIconNameChanged handler
func (p *OrgKdeWindow) AddThemedIconNameChangedHandler(h OrgKdeWindowThemedIconNameChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowThemedIconNameChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveThemedIconNameChangedHandler removes the ThemedIconNameChanged handler
func (p *OrgKdeWindow) RemoveThemedIconNameChangedHandler(h OrgKdeWindowThemedIconNameChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowThemedIconNameChangeds, h)
}

// OrgKdeWindowUnmappedHandler is the handler interface for OrgKdeWindowUnmappedEvent
type OrgKdeWindowUnmappedHandler interface {
	HandleOrgKdeWindowUnmapped(OrgKdeWindowUnmappedEvent)
}

// AddUnmappedHandler adds the Unmapped handler
func (p *OrgKdeWindow) AddUnmappedHandler(h OrgKdeWindowUnmappedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowUnmappeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveUnmappedHandler removes the Unmapped handler
func (p *OrgKdeWindow) RemoveUnmappedHandler(h OrgKdeWindowUnmappedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowUnmappeds, h)
}

// OrgKdeWindowInitialStateHandler is the handler interface for OrgKdeWindowInitialStateEvent
type OrgKdeWindowInitialStateHandler interface {
	HandleOrgKdeWindowInitialState(OrgKdeWindowInitialStateEvent)
}

// AddInitialStateHandler adds the InitialState handler
func (p *OrgKdeWindow) AddInitialStateHandler(h OrgKdeWindowInitialStateHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowInitialStates[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveInitialStateHandler removes the InitialState handler
func (p *OrgKdeWindow) RemoveInitialStateHandler(h OrgKdeWindowInitialStateHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowInitialStates, h)
}

// OrgKdeWindowParentWindowHandler is the handler interface for OrgKdeWindowParentWindowEvent
type OrgKdeWindowParentWindowHandler interface {
	HandleOrgKdeWindowParentWindow(OrgKdeWindowParentWindowEvent)
}

// AddParentWindowHandler adds the ParentWindow handler
func (p *OrgKdeWindow) AddParentWindowHandler(h OrgKdeWindowParentWindowHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowParentWindows[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveParentWindowHandler removes the ParentWindow handler
func (p *OrgKdeWindow) RemoveParentWindowHandler(h OrgKdeWindowParentWindowHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowParentWindows, h)
}

// OrgKdeWindowGeometryHandler is the handler interface for OrgKdeWindowGeometryEvent
type OrgKdeWindowGeometryHandler interface {
	HandleOrgKdeWindowGeometry(OrgKdeWindowGeometryEvent)
}

// AddGeometryHandler adds the Geometry handler
func (p *OrgKdeWindow) AddGeometryHandler(h OrgKdeWindowGeometryHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowGeometrys[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveGeometryHandler removes the Geometry handler
func (p *OrgKdeWindow) RemoveGeometryHandler(h OrgKdeWindowGeometryHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowGeometrys, h)
}

// OrgKdeWindowIconChangedHandler is the handler interface for OrgKdeWindowIconChangedEvent
type OrgKdeWindowIconChangedHandler interface {
	HandleOrgKdeWindowIconChanged(OrgKdeWindowIconChangedEvent)
}

// AddIconChangedHandler adds the IconChanged handler
func (p *OrgKdeWindow) AddIconChangedHandler(h OrgKdeWindowIconChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowIconChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveIconChangedHandler removes the IconChanged handler
func (p *OrgKdeWindow) RemoveIconChangedHandler(h OrgKdeWindowIconChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowIconChangeds, h)
}

// OrgKdeWindowPidChangedHandler is the handler interface for OrgKdeWindowPidChangedEvent
type OrgKdeWindowPidChangedHandler interface {
	HandleOrgKdeWindowPidChanged(OrgKdeWindowPidChangedEvent)
}

// AddPidChangedHandler adds the PidChanged handler
func (p *OrgKdeWindow) AddPidChangedHandler(h OrgKdeWindowPidChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowPidChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemovePidChangedHandler removes the PidChanged handler
func (p *OrgKdeWindow) RemovePidChangedHandler(h OrgKdeWindowPidChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowPidChangeds, h)
}

// OrgKdeWindowVirtualDesktopEnteredHandler is the handler interface for OrgKdeWindowVirtualDesktopEnteredEvent
type OrgKdeWindowVirtualDesktopEnteredHandler interface {
	HandleOrgKdeWindowVirtualDesktopEntered(OrgKdeWindowVirtualDesktopEnteredEvent)
}

// AddVirtualDesktopEnteredHandler adds the VirtualDesktopEntered handler
func (p *OrgKdeWindow) AddVirtualDesktopEnteredHandler(h OrgKdeWindowVirtualDesktopEnteredHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowVirtualDesktopEntereds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveVirtualDesktopEnteredHandler removes the VirtualDesktopEntered handler
func (p *OrgKdeWindow) RemoveVirtualDesktopEnteredHandler(h OrgKdeWindowVirtualDesktopEnteredHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowVirtualDesktopEntereds, h)
}

// OrgKdeWindowVirtualDesktopLeftHandler is the handler interface for OrgKdeWindowVirtualDesktopLeftEvent
type OrgKdeWindowVirtualDesktopLeftHandler interface {
	HandleOrgKdeWindowVirtualDesktopLeft(OrgKdeWindowVirtualDesktopLeftEvent)
}

// AddVirtualDesktopLeftHandler adds the VirtualDesktopLeft handler
func (p *OrgKdeWindow) AddVirtualDesktopLeftHandler(h OrgKdeWindowVirtualDesktopLeftHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowVirtualDesktopLefts[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveVirtualDesktopLeftHandler removes the VirtualDesktopLeft handler
func (p *OrgKdeWindow) RemoveVirtualDesktopLeftHandler(h OrgKdeWindowVirtualDesktopLeftHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowVirtualDesktopLefts, h)
}

// OrgKdeWindowApplicationMenuHandler is the handler interface for OrgKdeWindowApplicationMenuEvent
type OrgKdeWindowApplicationMenuHandler interface {
	HandleOrgKdeWindowApplicationMenu(OrgKdeWindowApplicationMenuEvent)
}

// AddApplicationMenuHandler adds the ApplicationMenu handler
func (p *OrgKdeWindow) AddApplicationMenuHandler(h OrgKdeWindowApplicationMenuHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowApplicationMenus[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveApplicationMenuHandler removes the ApplicationMenu handler
func (p *OrgKdeWindow) RemoveApplicationMenuHandler(h OrgKdeWindowApplicationMenuHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowApplicationMenus, h)
}

// OrgKdeWindowActivityEnteredHandler is the handler interface for OrgKdeWindowActivityEnteredEvent
type OrgKdeWindowActivityEnteredHandler interface {
	HandleOrgKdeWindowActivityEntered(OrgKdeWindowActivityEnteredEvent)
}

// AddActivityEnteredHandler adds the ActivityEntered handler
func (p *OrgKdeWindow) AddActivityEnteredHandler(h OrgKdeWindowActivityEnteredHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowActivityEntereds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveActivityEnteredHandler removes the ActivityEntered handler
func (p *OrgKdeWindow) RemoveActivityEnteredHandler(h OrgKdeWindowActivityEnteredHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowActivityEntereds, h)
}

// OrgKdeWindowActivityLeftHandler is the handler interface for OrgKdeWindowActivityLeftEvent
type OrgKdeWindowActivityLeftHandler interface {
	HandleOrgKdeWindowActivityLeft(OrgKdeWindowActivityLeftEvent)
}

// AddActivityLeftHandler adds the ActivityLeft handler
func (p *OrgKdeWindow) AddActivityLeftHandler(h OrgKdeWindowActivityLeftHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowActivityLefts[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveActivityLeftHandler removes the ActivityLeft handler
func (p *OrgKdeWindow) RemoveActivityLeftHandler(h OrgKdeWindowActivityLeftHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowActivityLefts, h)
}

// OrgKdeWindowResourceNameChangedHandler is the handler interface for OrgKdeWindowResourceNameChangedEvent
type OrgKdeWindowResourceNameChangedHandler interface {
	HandleOrgKdeWindowResourceNameChanged(OrgKdeWindowResourceNameChangedEvent)
}

// AddResourceNameChangedHandler adds the ResourceNameChanged handler
func (p *OrgKdeWindow) AddResourceNameChangedHandler(h OrgKdeWindowResourceNameChangedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowResourceNameChangeds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveResourceNameChangedHandler removes the ResourceNameChanged handler
func (p *OrgKdeWindow) RemoveResourceNameChangedHandler(h OrgKdeWindowResourceNameChangedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowResourceNameChangeds, h)
}

// OrgKdeWindowClientGeometryHandler is the handler interface for OrgKdeWindowClientGeometryEvent
type OrgKdeWindowClientGeometryHandler interface {
	HandleOrgKdeWindowClientGeometry(OrgKdeWindowClientGeometryEvent)
}

// AddClientGeometryHandler adds the ClientGeometry handler
func (p *OrgKdeWindow) AddClientGeometryHandler(h OrgKdeWindowClientGeometryHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeWindowClientGeometrys[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveClientGeometryHandler removes the ClientGeometry handler
func (p *OrgKdeWindow) RemoveClientGeometryHandler(h OrgKdeWindowClientGeometryHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeWindowClientGeometrys, h)
}

// OrgKdeActivationFeedback activation feedback
type OrgKdeActivationFeedback struct {
	BaseProxy
	mu                                         sync.RWMutex
	privateOrgKdeActivationFeedbackActivations map[OrgKdeActivationFeedbackActivationHandler]struct{}
}

// initOrgKdeActivationFeedback initializes the OrgKdeActivationFeedback object's handler maps
func (ret *OrgKdeActivationFeedback) initOrgKdeActivationFeedback() {
	ret.privateOrgKdeActivationFeedbackActivations = make(map[OrgKdeActivationFeedbackActivationHandler]struct{})
}

// NewOrgKdeActivationFeedback is a constructor for the OrgKdeActivationFeedback object
func NewOrgKdeActivationFeedback(ctx *Context) *OrgKdeActivationFeedback {
	ret := new(OrgKdeActivationFeedback)
	ret.initOrgKdeActivationFeedback()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the activation manager object
func (p *OrgKdeActivationFeedback) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object OrgKdeActivationFeedback
func (p *OrgKdeActivationFeedback) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateOrgKdeActivationFeedbackActivations) > 0 {
			ev := OrgKdeActivationFeedbackActivationEvent{}
			ev.Id = func() *OrgKdeActivation {
				ret := new(OrgKdeActivation)
				ret.initOrgKdeActivation()
				return event.NewId(ret, p.Context()).(*OrgKdeActivation)
			}()
			p.mu.RLock()
			for h := range p.privateOrgKdeActivationFeedbackActivations {
				h.HandleOrgKdeActivationFeedbackActivation(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// OrgKdeActivationFeedbackActivationEvent is the notify that an app is starting
type OrgKdeActivationFeedbackActivationEvent struct {
	// Id is the
	Id *OrgKdeActivation
}

// OrgKdeActivationFeedbackActivationHandler is the handler interface for OrgKdeActivationFeedbackActivationEvent
type OrgKdeActivationFeedbackActivationHandler interface {
	HandleOrgKdeActivationFeedbackActivation(OrgKdeActivationFeedbackActivationEvent)
}

// AddActivationHandler adds the Activation handler
func (p *OrgKdeActivationFeedback) AddActivationHandler(h OrgKdeActivationFeedbackActivationHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeActivationFeedbackActivations[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveActivationHandler removes the Activation handler
func (p *OrgKdeActivationFeedback) RemoveActivationHandler(h OrgKdeActivationFeedbackActivationHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeActivationFeedbackActivations, h)
}

// OrgKdeActivation
type OrgKdeActivation struct {
	BaseProxy
	mu                               sync.RWMutex
	privateOrgKdeActivationAppIds    map[OrgKdeActivationAppIdHandler]struct{}
	privateOrgKdeActivationFinisheds map[OrgKdeActivationFinishedHandler]struct{}
}

// initOrgKdeActivation initializes the OrgKdeActivation object's handler maps
func (ret *OrgKdeActivation) initOrgKdeActivation() {
	ret.privateOrgKdeActivationAppIds = make(map[OrgKdeActivationAppIdHandler]struct{})
	ret.privateOrgKdeActivationFinisheds = make(map[OrgKdeActivationFinishedHandler]struct{})
}

// NewOrgKdeActivation is a constructor for the OrgKdeActivation object
func NewOrgKdeActivation(ctx *Context) *OrgKdeActivation {
	ret := new(OrgKdeActivation)
	ret.initOrgKdeActivation()
	ctx.Register(ret)
	return ret
}

// Destroy destroy the org_kde_plasma_activation object
func (p *OrgKdeActivation) Destroy() error {

	return p.Context().SendRequest(p, 0)
}

// Dispatch dispatches event for object OrgKdeActivation
func (p *OrgKdeActivation) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateOrgKdeActivationAppIds) > 0 {
			ev := OrgKdeActivationAppIdEvent{}
			ev.AppId = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeActivationAppIds {
				h.HandleOrgKdeActivationAppId(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateOrgKdeActivationFinisheds) > 0 {
			ev := OrgKdeActivationFinishedEvent{}
			p.mu.RLock()
			for h := range p.privateOrgKdeActivationFinisheds {
				h.HandleOrgKdeActivationFinished(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// OrgKdeActivationAppIdEvent is the Offers the app_id
type OrgKdeActivationAppIdEvent struct {
	// AppId is the application id, as described in xdg_activation_v1
	AppId string
}

// OrgKdeActivationFinishedEvent is the Notifies about activation finished, either by activation or because it got invalidated
type OrgKdeActivationFinishedEvent struct {
}

// OrgKdeActivationAppIdHandler is the handler interface for OrgKdeActivationAppIdEvent
type OrgKdeActivationAppIdHandler interface {
	HandleOrgKdeActivationAppId(OrgKdeActivationAppIdEvent)
}

// AddAppIdHandler adds the AppId handler
func (p *OrgKdeActivation) AddAppIdHandler(h OrgKdeActivationAppIdHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeActivationAppIds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveAppIdHandler removes the AppId handler
func (p *OrgKdeActivation) RemoveAppIdHandler(h OrgKdeActivationAppIdHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeActivationAppIds, h)
}

// OrgKdeActivationFinishedHandler is the handler interface for OrgKdeActivationFinishedEvent
type OrgKdeActivationFinishedHandler interface {
	HandleOrgKdeActivationFinished(OrgKdeActivationFinishedEvent)
}

// AddFinishedHandler adds the Finished handler
func (p *OrgKdeActivation) AddFinishedHandler(h OrgKdeActivationFinishedHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeActivationFinisheds[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveFinishedHandler removes the Finished handler
func (p *OrgKdeActivation) RemoveFinishedHandler(h OrgKdeActivationFinishedHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeActivationFinisheds, h)
}

// OrgKdeStackingOrder helper object for sending the stacking order
type OrgKdeStackingOrder struct {
	BaseProxy
	mu                                sync.RWMutex
	privateOrgKdeStackingOrderWindows map[OrgKdeStackingOrderWindowHandler]struct{}
	privateOrgKdeStackingOrderDones   map[OrgKdeStackingOrderDoneHandler]struct{}
}

// initOrgKdeStackingOrder initializes the OrgKdeStackingOrder object's handler maps
func (ret *OrgKdeStackingOrder) initOrgKdeStackingOrder() {
	ret.privateOrgKdeStackingOrderWindows = make(map[OrgKdeStackingOrderWindowHandler]struct{})
	ret.privateOrgKdeStackingOrderDones = make(map[OrgKdeStackingOrderDoneHandler]struct{})
}

// NewOrgKdeStackingOrder is a constructor for the OrgKdeStackingOrder object
func NewOrgKdeStackingOrder(ctx *Context) *OrgKdeStackingOrder {
	ret := new(OrgKdeStackingOrder)
	ret.initOrgKdeStackingOrder()
	ctx.Register(ret)
	return ret
}

// Dispatch dispatches event for object OrgKdeStackingOrder
func (p *OrgKdeStackingOrder) Dispatch(event *Event) {
	switch event.Opcode {
	case 0:
		if len(p.privateOrgKdeStackingOrderWindows) > 0 {
			ev := OrgKdeStackingOrderWindowEvent{}
			ev.Uuid = event.String()
			p.mu.RLock()
			for h := range p.privateOrgKdeStackingOrderWindows {
				h.HandleOrgKdeStackingOrderWindow(ev)
			}
			p.mu.RUnlock()
		}
	case 1:
		if len(p.privateOrgKdeStackingOrderDones) > 0 {
			ev := OrgKdeStackingOrderDoneEvent{}
			p.mu.RLock()
			for h := range p.privateOrgKdeStackingOrderDones {
				h.HandleOrgKdeStackingOrderDone(ev)
			}
			p.mu.RUnlock()
		}

	}
}

// OrgKdeStackingOrderWindowEvent is the a window in the stacking order list
type OrgKdeStackingOrderWindowEvent struct {
	// Uuid is the window uuid
	Uuid string
}

// OrgKdeStackingOrderDoneEvent is the marks the end of the list
type OrgKdeStackingOrderDoneEvent struct {
}

// OrgKdeStackingOrderWindowHandler is the handler interface for OrgKdeStackingOrderWindowEvent
type OrgKdeStackingOrderWindowHandler interface {
	HandleOrgKdeStackingOrderWindow(OrgKdeStackingOrderWindowEvent)
}

// AddWindowHandler adds the Window handler
func (p *OrgKdeStackingOrder) AddWindowHandler(h OrgKdeStackingOrderWindowHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeStackingOrderWindows[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveWindowHandler removes the Window handler
func (p *OrgKdeStackingOrder) RemoveWindowHandler(h OrgKdeStackingOrderWindowHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeStackingOrderWindows, h)
}

// OrgKdeStackingOrderDoneHandler is the handler interface for OrgKdeStackingOrderDoneEvent
type OrgKdeStackingOrderDoneHandler interface {
	HandleOrgKdeStackingOrderDone(OrgKdeStackingOrderDoneEvent)
}

// AddDoneHandler adds the Done handler
func (p *OrgKdeStackingOrder) AddDoneHandler(h OrgKdeStackingOrderDoneHandler) {
	if h != nil {
		p.mu.Lock()
		p.privateOrgKdeStackingOrderDones[h] = struct{}{}
		p.mu.Unlock()
	}
}

// RemoveDoneHandler removes the Done handler
func (p *OrgKdeStackingOrder) RemoveDoneHandler(h OrgKdeStackingOrderDoneHandler) {
	p.mu.Lock()
	defer p.mu.Unlock()

	delete(p.privateOrgKdeStackingOrderDones, h)
}
